//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         Access policies for an EHR Extract.
 *       
 * 
 * <p>Java class for AccessPolicy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccessPolicy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="policyId" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="author" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="dateCommitted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="previousVersion" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="effectiveStart" type="{uri:iso.org:21090}TS" minOccurs="0"/>
 *         &lt;element name="effectiveEnd" type="{uri:iso.org:21090}TS" minOccurs="0"/>
 *         &lt;element name="policyAttestation" type="{http://www.iso.org/iso/search.htm?qt=13606}Attestation" maxOccurs="unbounded"/>
 *         &lt;element name="ehrTarget" type="{http://www.iso.org/iso/search.htm?qt=13606}Target" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="requestCharacteristics" type="{http://www.iso.org/iso/search.htm?qt=13606}Request" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="accessRules" type="{http://www.iso.org/iso/search.htm?qt=13606}MaxSensitivityConstraints"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccessPolicy", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "policyId",
    "author",
    "dateCommitted",
    "previousVersion",
    "effectiveStart",
    "effectiveEnd",
    "policyAttestation",
    "ehrTarget",
    "requestCharacteristics",
    "accessRules"
})
public class AccessPolicy {

    @XmlElement(namespace = "", required = true)
    protected II policyId;
    @XmlElement(namespace = "", required = true)
    protected II author;
    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCommitted;
    @XmlElement(namespace = "")
    protected II previousVersion;
    @XmlElement(namespace = "")
    protected TS effectiveStart;
    @XmlElement(namespace = "")
    protected TS effectiveEnd;
    @XmlElement(namespace = "", required = true)
    protected List<Attestation> policyAttestation;
    @XmlElement(namespace = "")
    protected List<Target> ehrTarget;
    @XmlElement(namespace = "")
    protected List<Request> requestCharacteristics;
    @XmlElement(namespace = "", required = true)
    protected MaxSensitivityConstraints accessRules;

    /**
     * Gets the value of the policyId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getPolicyId() {
        return policyId;
    }

    /**
     * Sets the value of the policyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setPolicyId(II value) {
        this.policyId = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setAuthor(II value) {
        this.author = value;
    }

    /**
     * Gets the value of the dateCommitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCommitted() {
        return dateCommitted;
    }

    /**
     * Sets the value of the dateCommitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCommitted(XMLGregorianCalendar value) {
        this.dateCommitted = value;
    }

    /**
     * Gets the value of the previousVersion property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getPreviousVersion() {
        return previousVersion;
    }

    /**
     * Sets the value of the previousVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setPreviousVersion(II value) {
        this.previousVersion = value;
    }

    /**
     * Gets the value of the effectiveStart property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getEffectiveStart() {
        return effectiveStart;
    }

    /**
     * Sets the value of the effectiveStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setEffectiveStart(TS value) {
        this.effectiveStart = value;
    }

    /**
     * Gets the value of the effectiveEnd property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getEffectiveEnd() {
        return effectiveEnd;
    }

    /**
     * Sets the value of the effectiveEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setEffectiveEnd(TS value) {
        this.effectiveEnd = value;
    }

    /**
     * Gets the value of the policyAttestation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyAttestation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyAttestation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attestation }
     * 
     * 
     */
    public List<Attestation> getPolicyAttestation() {
        if (policyAttestation == null) {
            policyAttestation = new ArrayList<Attestation>();
        }
        return this.policyAttestation;
    }

    /**
     * Gets the value of the ehrTarget property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ehrTarget property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEhrTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Target }
     * 
     * 
     */
    public List<Target> getEhrTarget() {
        if (ehrTarget == null) {
            ehrTarget = new ArrayList<Target>();
        }
        return this.ehrTarget;
    }

    /**
     * Gets the value of the requestCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the requestCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRequestCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Request }
     * 
     * 
     */
    public List<Request> getRequestCharacteristics() {
        if (requestCharacteristics == null) {
            requestCharacteristics = new ArrayList<Request>();
        }
        return this.requestCharacteristics;
    }

    /**
     * Gets the value of the accessRules property.
     * 
     * @return
     *     possible object is
     *     {@link MaxSensitivityConstraints }
     *     
     */
    public MaxSensitivityConstraints getAccessRules() {
        return accessRules;
    }

    /**
     * Sets the value of the accessRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaxSensitivityConstraints }
     *     
     */
    public void setAccessRules(MaxSensitivityConstraints value) {
        this.accessRules = value;
    }

}
