//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AD">
 *   &lt;complexContent>
 *     &lt;extension base="{uri:iso.org:21090}ANY">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="part" type="{uri:iso.org:21090}ADXP"/>
 *           &lt;element name="br" type="{uri:iso.org:21090}ADXP.BR"/>
 *           &lt;element name="addressLine" type="{uri:iso.org:21090}ADXP.AL"/>
 *           &lt;element name="additionalLocator" type="{uri:iso.org:21090}ADXP.ADL"/>
 *           &lt;element name="unitID" type="{uri:iso.org:21090}ADXP.UNID"/>
 *           &lt;element name="unitType" type="{uri:iso.org:21090}ADXP.UNIT"/>
 *           &lt;element name="deliveryAddressLine" type="{uri:iso.org:21090}ADXP.DAL"/>
 *           &lt;element name="deliveryInstallationType" type="{uri:iso.org:21090}ADXP.DINST"/>
 *           &lt;element name="deliveryInstallationArea" type="{uri:iso.org:21090}ADXP.DINSTA"/>
 *           &lt;element name="deliveryInstallationQualifier" type="{uri:iso.org:21090}ADXP.DINSTQ"/>
 *           &lt;element name="deliveryMode" type="{uri:iso.org:21090}ADXP.DMOD"/>
 *           &lt;element name="deliveryModeIdentifier" type="{uri:iso.org:21090}ADXP.DMODID"/>
 *           &lt;element name="streetAddressLine" type="{uri:iso.org:21090}ADXP.SAL"/>
 *           &lt;element name="houseNumber" type="{uri:iso.org:21090}ADXP.BNR"/>
 *           &lt;element name="houseNumberNumeric" type="{uri:iso.org:21090}ADXP.BNN"/>
 *           &lt;element name="buildingNumberSuffix" type="{uri:iso.org:21090}ADXP.BNS"/>
 *           &lt;element name="streetName" type="{uri:iso.org:21090}ADXP.STR"/>
 *           &lt;element name="streetNameBase" type="{uri:iso.org:21090}ADXP.STB"/>
 *           &lt;element name="streetType" type="{uri:iso.org:21090}ADXP.STTYP"/>
 *           &lt;element name="intersection" type="{uri:iso.org:21090}ADXP.INT"/>
 *           &lt;element name="direction" type="{uri:iso.org:21090}ADXP.DIR"/>
 *           &lt;element name="careOf" type="{uri:iso.org:21090}ADXP.CAR"/>
 *           &lt;element name="censusTract" type="{uri:iso.org:21090}ADXP.CEN"/>
 *           &lt;element name="country" type="{uri:iso.org:21090}ADXP.CNT"/>
 *           &lt;element name="county" type="{uri:iso.org:21090}ADXP.CPA"/>
 *           &lt;element name="city" type="{uri:iso.org:21090}ADXP.CTY"/>
 *           &lt;element name="postBox" type="{uri:iso.org:21090}ADXP.POB"/>
 *           &lt;element name="precinct" type="{uri:iso.org:21090}ADXP.PRE"/>
 *           &lt;element name="state" type="{uri:iso.org:21090}ADXP.STA"/>
 *           &lt;element name="postalCode" type="{uri:iso.org:21090}ADXP.ZIP"/>
 *         &lt;/choice>
 *         &lt;element name="useablePeriod" type="{uri:iso.org:21090}QSET_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="use" type="{uri:iso.org:21090}set_PostalAddressUse" />
 *       &lt;attribute name="isNotOrdered" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AD", propOrder = {
    "partOrBrOrAddressLine",
    "useablePeriod"
})
public class AD
    extends ANY
{

    @XmlElements({
        @XmlElement(name = "direction", type = ADXPDIR.class),
        @XmlElement(name = "streetAddressLine", type = ADXPSAL.class),
        @XmlElement(name = "postalCode", type = ADXPZIP.class),
        @XmlElement(name = "intersection", type = ADXPINT.class),
        @XmlElement(name = "br", type = ADXPBR.class),
        @XmlElement(name = "houseNumberNumeric", type = ADXPBNN.class),
        @XmlElement(name = "postBox", type = ADXPPOB.class),
        @XmlElement(name = "addressLine", type = ADXPAL.class),
        @XmlElement(name = "part"),
        @XmlElement(name = "deliveryInstallationType", type = ADXPDINST.class),
        @XmlElement(name = "city", type = ADXPCTY.class),
        @XmlElement(name = "state", type = ADXPSTA.class),
        @XmlElement(name = "deliveryMode", type = ADXPDMOD.class),
        @XmlElement(name = "precinct", type = ADXPPRE.class),
        @XmlElement(name = "deliveryModeIdentifier", type = ADXPDMODID.class),
        @XmlElement(name = "buildingNumberSuffix", type = ADXPBNS.class),
        @XmlElement(name = "deliveryInstallationQualifier", type = ADXPDINSTQ.class),
        @XmlElement(name = "streetName", type = ADXPSTR.class),
        @XmlElement(name = "streetType", type = ADXPSTTYP.class),
        @XmlElement(name = "careOf", type = ADXPCAR.class),
        @XmlElement(name = "county", type = ADXPCPA.class),
        @XmlElement(name = "deliveryAddressLine", type = ADXPDAL.class),
        @XmlElement(name = "unitType", type = ADXPUNIT.class),
        @XmlElement(name = "unitID", type = ADXPUNID.class),
        @XmlElement(name = "houseNumber", type = ADXPBNR.class),
        @XmlElement(name = "streetNameBase", type = ADXPSTB.class),
        @XmlElement(name = "censusTract", type = ADXPCEN.class),
        @XmlElement(name = "country", type = ADXPCNT.class),
        @XmlElement(name = "deliveryInstallationArea", type = ADXPDINSTA.class),
        @XmlElement(name = "additionalLocator", type = ADXPADL.class)
    })
    protected List<ADXP> partOrBrOrAddressLine;
    protected QSETTS useablePeriod;
    @XmlAttribute(name = "use")
    protected List<PostalAddressUse> use;
    @XmlAttribute(name = "isNotOrdered")
    protected Boolean isNotOrdered;

    /**
     * Gets the value of the partOrBrOrAddressLine property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partOrBrOrAddressLine property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartOrBrOrAddressLine().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ADXPDIR }
     * {@link ADXPSAL }
     * {@link ADXPZIP }
     * {@link ADXPINT }
     * {@link ADXPBR }
     * {@link ADXPBNN }
     * {@link ADXPPOB }
     * {@link ADXPAL }
     * {@link ADXP }
     * {@link ADXPDINST }
     * {@link ADXPCTY }
     * {@link ADXPSTA }
     * {@link ADXPDMOD }
     * {@link ADXPPRE }
     * {@link ADXPDMODID }
     * {@link ADXPBNS }
     * {@link ADXPDINSTQ }
     * {@link ADXPSTR }
     * {@link ADXPSTTYP }
     * {@link ADXPCAR }
     * {@link ADXPCPA }
     * {@link ADXPDAL }
     * {@link ADXPUNIT }
     * {@link ADXPUNID }
     * {@link ADXPBNR }
     * {@link ADXPSTB }
     * {@link ADXPCEN }
     * {@link ADXPCNT }
     * {@link ADXPDINSTA }
     * {@link ADXPADL }
     * 
     * 
     */
    public List<ADXP> getPartOrBrOrAddressLine() {
        if (partOrBrOrAddressLine == null) {
            partOrBrOrAddressLine = new ArrayList<ADXP>();
        }
        return this.partOrBrOrAddressLine;
    }

    /**
     * Gets the value of the useablePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link QSETTS }
     *     
     */
    public QSETTS getUseablePeriod() {
        return useablePeriod;
    }

    /**
     * Sets the value of the useablePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link QSETTS }
     *     
     */
    public void setUseablePeriod(QSETTS value) {
        this.useablePeriod = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the use property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PostalAddressUse }
     * 
     * 
     */
    public List<PostalAddressUse> getUse() {
        if (use == null) {
            use = new ArrayList<PostalAddressUse>();
        }
        return this.use;
    }

    /**
     * Gets the value of the isNotOrdered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsNotOrdered() {
        return isNotOrdered;
    }

    /**
     * Sets the value of the isNotOrdered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsNotOrdered(Boolean value) {
        this.isNotOrdered = value;
    }

}
