//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         Any  attestations  for a Record Component.  The proof field
 *         should be a  cryptographic  hash of the RecordComponent  it
 *         attests,  but it is recognised that in many implementations
 *         the components will change to  point to new components that
 *         revise  them.  In  that case,  the  proof  should sign  the
 *         unchanging parts of the component only.
 *       
 * 
 * <p>Java class for AttestationInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttestationInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attestedView" type="{uri:iso.org:21090}ED" minOccurs="0"/>
 *         &lt;element name="proof" type="{uri:iso.org:21090}ED" minOccurs="0"/>
 *         &lt;element name="reasonForAttestation" type="{uri:iso.org:21090}CD.CV"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="targetRcId" type="{uri:iso.org:21090}II" maxOccurs="unbounded"/>
 *         &lt;element name="attester" type="{http://www.iso.org/iso/search.htm?qt=13606}FunctionalRole"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttestationInfo", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "attestedView",
    "proof",
    "reasonForAttestation",
    "time",
    "targetRcId",
    "attester"
})
public class AttestationInfo {

    @XmlElement(namespace = "")
    protected ED attestedView;
    @XmlElement(namespace = "")
    protected ED proof;
    @XmlElement(namespace = "", required = true)
    protected CDCV reasonForAttestation;
    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar time;
    @XmlElement(namespace = "", required = true)
    protected List<II> targetRcId;
    @XmlElement(namespace = "", required = true)
    protected FunctionalRole attester;

    /**
     * Gets the value of the attestedView property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getAttestedView() {
        return attestedView;
    }

    /**
     * Sets the value of the attestedView property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setAttestedView(ED value) {
        this.attestedView = value;
    }

    /**
     * Gets the value of the proof property.
     * 
     * @return
     *     possible object is
     *     {@link ED }
     *     
     */
    public ED getProof() {
        return proof;
    }

    /**
     * Sets the value of the proof property.
     * 
     * @param value
     *     allowed object is
     *     {@link ED }
     *     
     */
    public void setProof(ED value) {
        this.proof = value;
    }

    /**
     * Gets the value of the reasonForAttestation property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getReasonForAttestation() {
        return reasonForAttestation;
    }

    /**
     * Sets the value of the reasonForAttestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setReasonForAttestation(CDCV value) {
        this.reasonForAttestation = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTime(XMLGregorianCalendar value) {
        this.time = value;
    }

    /**
     * Gets the value of the targetRcId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetRcId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetRcId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getTargetRcId() {
        if (targetRcId == null) {
            targetRcId = new ArrayList<II>();
        }
        return this.targetRcId;
    }

    /**
     * Gets the value of the attester property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalRole }
     *     
     */
    public FunctionalRole getAttester() {
        return attester;
    }

    /**
     * Sets the value of the attester property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalRole }
     *     
     */
    public void setAttester(FunctionalRole value) {
        this.attester = value;
    }

}
