//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         The  committal  and revision  data for a  Record Component.
 *         Note   that  the   invariant  is   incorrectly  stated   as 
 *         constraining  "attribute_version_status.coding_scheme_name"
 *         in the printed standard.
 *       
 * 
 * <p>Java class for AuditInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="committer" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="ehrSystem" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="previousVersion" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="reasonForRevision" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="timeCommitted" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="versionSetId" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="versionStatus" type="{http://www.iso.org/iso/search.htm?qt=13606}VersionStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditInfo", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "committer",
    "ehrSystem",
    "previousVersion",
    "reasonForRevision",
    "timeCommitted",
    "versionSetId",
    "versionStatus"
})
public class AuditInfo {

    @XmlElement(namespace = "", required = true)
    protected II committer;
    @XmlElement(namespace = "", required = true)
    protected II ehrSystem;
    @XmlElement(namespace = "")
    protected II previousVersion;
    @XmlElement(namespace = "")
    protected CDCV reasonForRevision;
    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeCommitted;
    @XmlElement(namespace = "")
    protected II versionSetId;
    @XmlElement(namespace = "")
    protected VersionStatus versionStatus;

    /**
     * Gets the value of the committer property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getCommitter() {
        return committer;
    }

    /**
     * Sets the value of the committer property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setCommitter(II value) {
        this.committer = value;
    }

    /**
     * Gets the value of the ehrSystem property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getEhrSystem() {
        return ehrSystem;
    }

    /**
     * Sets the value of the ehrSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setEhrSystem(II value) {
        this.ehrSystem = value;
    }

    /**
     * Gets the value of the previousVersion property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getPreviousVersion() {
        return previousVersion;
    }

    /**
     * Sets the value of the previousVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setPreviousVersion(II value) {
        this.previousVersion = value;
    }

    /**
     * Gets the value of the reasonForRevision property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getReasonForRevision() {
        return reasonForRevision;
    }

    /**
     * Sets the value of the reasonForRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setReasonForRevision(CDCV value) {
        this.reasonForRevision = value;
    }

    /**
     * Gets the value of the timeCommitted property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeCommitted() {
        return timeCommitted;
    }

    /**
     * Sets the value of the timeCommitted property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeCommitted(XMLGregorianCalendar value) {
        this.timeCommitted = value;
    }

    /**
     * Gets the value of the versionSetId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getVersionSetId() {
        return versionSetId;
    }

    /**
     * Sets the value of the versionSetId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setVersionSetId(II value) {
        this.versionSetId = value;
    }

    /**
     * Gets the value of the versionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VersionStatus }
     *     
     */
    public VersionStatus getVersionStatus() {
        return versionStatus;
    }

    /**
     * Sets the value of the versionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionStatus }
     *     
     */
    public void setVersionStatus(VersionStatus value) {
        this.versionStatus = value;
    }

}
