//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Key  aggregation  class  representing  the  set  of  Record
 *         Components authored and committed during a  single clinical
 *         encounter.  Note the  values for  territory  will  indicate
 *         the legal  framework under which  the  data was  committed.
 *       
 * 
 * <p>Java class for Composition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Composition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iso.org/iso/search.htm?qt=13606}RecordComponent">
 *       &lt;sequence>
 *         &lt;element name="contributionId" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="sessionTime" type="{uri:iso.org:21090}IVL_TS" minOccurs="0"/>
 *         &lt;element name="territory" type="{http://www.codesynthesis.com/xmlns/xsstl}ISO3166CountyCode" minOccurs="0"/>
 *         &lt;element name="attestations" type="{http://www.iso.org/iso/search.htm?qt=13606}AttestationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="otherParticipations" type="{http://www.iso.org/iso/search.htm?qt=13606}FunctionalRole" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="committal" type="{http://www.iso.org/iso/search.htm?qt=13606}AuditInfo"/>
 *         &lt;element name="content" type="{http://www.iso.org/iso/search.htm?qt=13606}Content" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="composer" type="{http://www.iso.org/iso/search.htm?qt=13606}FunctionalRole" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Composition", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "contributionId",
    "sessionTime",
    "territory",
    "attestations",
    "otherParticipations",
    "committal",
    "content",
    "composer"
})
public class Composition
    extends RecordComponent
{

    @XmlElement(namespace = "")
    protected II contributionId;
    @XmlElement(namespace = "")
    protected IVLTS sessionTime;
    @XmlElement(namespace = "")
    protected ISO3166CountyCode territory;
    @XmlElement(namespace = "")
    protected List<AttestationInfo> attestations;
    @XmlElement(namespace = "")
    protected List<FunctionalRole> otherParticipations;
    @XmlElement(namespace = "", required = true)
    protected AuditInfo committal;
    @XmlElement(namespace = "")
    protected List<Content> content;
    @XmlElement(namespace = "")
    protected FunctionalRole composer;

    /**
     * Gets the value of the contributionId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getContributionId() {
        return contributionId;
    }

    /**
     * Sets the value of the contributionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setContributionId(II value) {
        this.contributionId = value;
    }

    /**
     * Gets the value of the sessionTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getSessionTime() {
        return sessionTime;
    }

    /**
     * Sets the value of the sessionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setSessionTime(IVLTS value) {
        this.sessionTime = value;
    }

    /**
     * Gets the value of the territory property.
     * 
     * @return
     *     possible object is
     *     {@link ISO3166CountyCode }
     *     
     */
    public ISO3166CountyCode getTerritory() {
        return territory;
    }

    /**
     * Sets the value of the territory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO3166CountyCode }
     *     
     */
    public void setTerritory(ISO3166CountyCode value) {
        this.territory = value;
    }

    /**
     * Gets the value of the attestations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attestations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttestations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttestationInfo }
     * 
     * 
     */
    public List<AttestationInfo> getAttestations() {
        if (attestations == null) {
            attestations = new ArrayList<AttestationInfo>();
        }
        return this.attestations;
    }

    /**
     * Gets the value of the otherParticipations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherParticipations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherParticipations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FunctionalRole }
     * 
     * 
     */
    public List<FunctionalRole> getOtherParticipations() {
        if (otherParticipations == null) {
            otherParticipations = new ArrayList<FunctionalRole>();
        }
        return this.otherParticipations;
    }

    /**
     * Gets the value of the committal property.
     * 
     * @return
     *     possible object is
     *     {@link AuditInfo }
     *     
     */
    public AuditInfo getCommittal() {
        return committal;
    }

    /**
     * Sets the value of the committal property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditInfo }
     *     
     */
    public void setCommittal(AuditInfo value) {
        this.committal = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Content }
     * 
     * 
     */
    public List<Content> getContent() {
        if (content == null) {
            content = new ArrayList<Content>();
        }
        return this.content;
    }

    /**
     * Gets the value of the composer property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionalRole }
     *     
     */
    public FunctionalRole getComposer() {
        return composer;
    }

    /**
     * Sets the value of the composer property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionalRole }
     *     
     */
    public void setComposer(FunctionalRole value) {
        this.composer = value;
    }

}
