//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Root class containing the Audit Log in a communicable form.
 * 				The parties  to this  Audit Log Extract.   Note that part 4
 * 				refers  to an EX_PARTY  class that  has since been  removed
 * 				from  part 1.   It is  replaced by  IdentifiedEntity.   The
 * 				cardinality is not given, however.
 * 		  
 * 
 * <p>Java class for DemographicExtract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DemographicExtract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parties" type="{http://www.iso.org/iso/search.htm?qt=13606}IdentifiedEntity" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DemographicExtract", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "parties"
})
public class DemographicExtract {

    @XmlElement(namespace = "")
    protected List<IdentifiedEntity> parties;

    /**
     * Gets the value of the parties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifiedEntity }
     * 
     * 
     */
    public List<IdentifiedEntity> getParties() {
        if (parties == null) {
            parties = new ArrayList<IdentifiedEntity>();
        }
        return this.parties;
    }

}
