//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Defines the filter  that has been  applied when  generating
 *         this audit log extract. Integer sensitivity is corrected to
 *         Sensitivity type here. BL is now boolean.
 *       
 * 
 * <p>Java class for EHRAuditLogEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EHRAuditLogEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="purpose" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="responseDt" type="{uri:iso.org:21090}TS"/>
 *         &lt;element name="recipient" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="reasonForRefusal" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="otherResponseDetails" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="archetypeIds" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rcIds" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="timePeriod" type="{uri:iso.org:21090}IVL_TS" minOccurs="0"/>
 *         &lt;element name="allVersions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="descriptionOfData" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EHRAuditLogEntry", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "purpose",
    "responseDt",
    "recipient",
    "reasonForRefusal",
    "otherResponseDetails",
    "archetypeIds",
    "rcIds",
    "timePeriod",
    "allVersions",
    "descriptionOfData"
})
public class EHRAuditLogEntry {

    @XmlElement(namespace = "")
    protected CDCV purpose;
    @XmlElement(namespace = "", required = true)
    protected TS responseDt;
    @XmlElement(namespace = "")
    protected II recipient;
    @XmlElement(namespace = "")
    protected CDCV reasonForRefusal;
    @XmlElement(namespace = "")
    protected CDCV otherResponseDetails;
    @XmlElement(namespace = "")
    protected List<II> archetypeIds;
    @XmlElement(namespace = "")
    protected List<II> rcIds;
    @XmlElement(namespace = "")
    protected IVLTS timePeriod;
    @XmlElement(namespace = "")
    protected Boolean allVersions;
    @XmlElement(namespace = "")
    protected CDCV descriptionOfData;

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setPurpose(CDCV value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the responseDt property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getResponseDt() {
        return responseDt;
    }

    /**
     * Sets the value of the responseDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setResponseDt(TS value) {
        this.responseDt = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setRecipient(II value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the reasonForRefusal property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getReasonForRefusal() {
        return reasonForRefusal;
    }

    /**
     * Sets the value of the reasonForRefusal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setReasonForRefusal(CDCV value) {
        this.reasonForRefusal = value;
    }

    /**
     * Gets the value of the otherResponseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getOtherResponseDetails() {
        return otherResponseDetails;
    }

    /**
     * Sets the value of the otherResponseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setOtherResponseDetails(CDCV value) {
        this.otherResponseDetails = value;
    }

    /**
     * Gets the value of the archetypeIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archetypeIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchetypeIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getArchetypeIds() {
        if (archetypeIds == null) {
            archetypeIds = new ArrayList<II>();
        }
        return this.archetypeIds;
    }

    /**
     * Gets the value of the rcIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rcIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRcIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getRcIds() {
        if (rcIds == null) {
            rcIds = new ArrayList<II>();
        }
        return this.rcIds;
    }

    /**
     * Gets the value of the timePeriod property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getTimePeriod() {
        return timePeriod;
    }

    /**
     * Sets the value of the timePeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setTimePeriod(IVLTS value) {
        this.timePeriod = value;
    }

    /**
     * Gets the value of the allVersions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllVersions() {
        return allVersions;
    }

    /**
     * Sets the value of the allVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllVersions(Boolean value) {
        this.allVersions = value;
    }

    /**
     * Gets the value of the descriptionOfData property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getDescriptionOfData() {
        return descriptionOfData;
    }

    /**
     * Sets the value of the descriptionOfData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setDescriptionOfData(CDCV value) {
        this.descriptionOfData = value;
    }

}
