//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         Root class containing the Audit Log in a communicable form.
 *         Note that part 4 gives  "timeCreated"  as having type "II",
 *         and this has been corrected to "TS" in this implementation.
 *         Also,  the  standard  does not  provide  labels for  linked 
 *         classes and these have been inferred.
 *       
 * 
 * <p>Java class for EHRAuditLogExtract complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EHRAuditLogExtract">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ehrSystem" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="ehrId" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="subjectOfCare" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="timeCreated" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="hcaAuthorising" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="demographicExtract" type="{http://www.iso.org/iso/search.htm?qt=13606}DemographicExtract" minOccurs="0"/>
 *         &lt;element name="auditLogConstraints" type="{http://www.iso.org/iso/search.htm?qt=13606}AuditLogConstraints" minOccurs="0"/>
 *         &lt;element name="ehrAuditLogEntry" type="{http://www.iso.org/iso/search.htm?qt=13606}EHRAuditLogEntry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EHRAuditLogExtract", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "ehrSystem",
    "ehrId",
    "subjectOfCare",
    "timeCreated",
    "hcaAuthorising",
    "demographicExtract",
    "auditLogConstraints",
    "ehrAuditLogEntry"
})
public class EHRAuditLogExtract {

    @XmlElement(namespace = "", required = true)
    protected II ehrSystem;
    @XmlElement(namespace = "", required = true)
    protected II ehrId;
    @XmlElement(namespace = "", required = true)
    protected II subjectOfCare;
    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeCreated;
    @XmlElement(namespace = "")
    protected II hcaAuthorising;
    @XmlElement(namespace = "")
    protected DemographicExtract demographicExtract;
    @XmlElement(namespace = "")
    protected AuditLogConstraints auditLogConstraints;
    @XmlElement(namespace = "")
    protected List<EHRAuditLogEntry> ehrAuditLogEntry;

    /**
     * Gets the value of the ehrSystem property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getEhrSystem() {
        return ehrSystem;
    }

    /**
     * Sets the value of the ehrSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setEhrSystem(II value) {
        this.ehrSystem = value;
    }

    /**
     * Gets the value of the ehrId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getEhrId() {
        return ehrId;
    }

    /**
     * Sets the value of the ehrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setEhrId(II value) {
        this.ehrId = value;
    }

    /**
     * Gets the value of the subjectOfCare property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSubjectOfCare() {
        return subjectOfCare;
    }

    /**
     * Sets the value of the subjectOfCare property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSubjectOfCare(II value) {
        this.subjectOfCare = value;
    }

    /**
     * Gets the value of the timeCreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeCreated() {
        return timeCreated;
    }

    /**
     * Sets the value of the timeCreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeCreated(XMLGregorianCalendar value) {
        this.timeCreated = value;
    }

    /**
     * Gets the value of the hcaAuthorising property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getHcaAuthorising() {
        return hcaAuthorising;
    }

    /**
     * Sets the value of the hcaAuthorising property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setHcaAuthorising(II value) {
        this.hcaAuthorising = value;
    }

    /**
     * Gets the value of the demographicExtract property.
     * 
     * @return
     *     possible object is
     *     {@link DemographicExtract }
     *     
     */
    public DemographicExtract getDemographicExtract() {
        return demographicExtract;
    }

    /**
     * Sets the value of the demographicExtract property.
     * 
     * @param value
     *     allowed object is
     *     {@link DemographicExtract }
     *     
     */
    public void setDemographicExtract(DemographicExtract value) {
        this.demographicExtract = value;
    }

    /**
     * Gets the value of the auditLogConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link AuditLogConstraints }
     *     
     */
    public AuditLogConstraints getAuditLogConstraints() {
        return auditLogConstraints;
    }

    /**
     * Sets the value of the auditLogConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditLogConstraints }
     *     
     */
    public void setAuditLogConstraints(AuditLogConstraints value) {
        this.auditLogConstraints = value;
    }

    /**
     * Gets the value of the ehrAuditLogEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ehrAuditLogEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEhrAuditLogEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EHRAuditLogEntry }
     * 
     * 
     */
    public List<EHRAuditLogEntry> getEhrAuditLogEntry() {
        if (ehrAuditLogEntry == null) {
            ehrAuditLogEntry = new ArrayList<EHRAuditLogEntry>();
        }
        return this.ehrAuditLogEntry;
    }

}
