//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Organises and groups Compositions within an EHR Extract.
 *       
 * 
 * <p>Java class for Folder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Folder">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iso.org/iso/search.htm?qt=13606}RecordComponent">
 *       &lt;sequence>
 *         &lt;element name="subFolders" type="{http://www.iso.org/iso/search.htm?qt=13606}Folder" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attestations" type="{http://www.iso.org/iso/search.htm?qt=13606}AttestationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="compositionsRcId" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Folder", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "subFolders",
    "attestations",
    "compositionsRcId"
})
public class Folder
    extends RecordComponent
{

    @XmlElement(namespace = "")
    protected List<Folder> subFolders;
    @XmlElement(namespace = "")
    protected List<AttestationInfo> attestations;
    @XmlElement(namespace = "")
    protected List<II> compositionsRcId;

    /**
     * Gets the value of the subFolders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subFolders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubFolders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Folder }
     * 
     * 
     */
    public List<Folder> getSubFolders() {
        if (subFolders == null) {
            subFolders = new ArrayList<Folder>();
        }
        return this.subFolders;
    }

    /**
     * Gets the value of the attestations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attestations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttestations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttestationInfo }
     * 
     * 
     */
    public List<AttestationInfo> getAttestations() {
        if (attestations == null) {
            attestations = new ArrayList<AttestationInfo>();
        }
        return this.attestations;
    }

    /**
     * Gets the value of the compositionsRcId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compositionsRcId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompositionsRcId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getCompositionsRcId() {
        if (compositionsRcId == null) {
            compositionsRcId = new ArrayList<II>();
        }
        return this.compositionsRcId;
    }

}
