//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FunctionalRoles.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FunctionalRoles">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="subjectOfCare"/>
 *     &lt;enumeration value="subjectOfCareAgent"/>
 *     &lt;enumeration value="personalHealthcareProfessional"/>
 *     &lt;enumeration value="privilegedHealthcareProfessional"/>
 *     &lt;enumeration value="healthcareProfessional"/>
 *     &lt;enumeration value="healthRelatedProfessional"/>
 *     &lt;enumeration value="administrator"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FunctionalRoles", namespace = "http://www.iso.org/iso/search.htm?qt=13606")
@XmlEnum
public enum FunctionalRoles {

    @XmlEnumValue("subjectOfCare")
    SUBJECT_OF_CARE("subjectOfCare"),
    @XmlEnumValue("subjectOfCareAgent")
    SUBJECT_OF_CARE_AGENT("subjectOfCareAgent"),
    @XmlEnumValue("personalHealthcareProfessional")
    PERSONAL_HEALTHCARE_PROFESSIONAL("personalHealthcareProfessional"),
    @XmlEnumValue("privilegedHealthcareProfessional")
    PRIVILEGED_HEALTHCARE_PROFESSIONAL("privilegedHealthcareProfessional"),
    @XmlEnumValue("healthcareProfessional")
    HEALTHCARE_PROFESSIONAL("healthcareProfessional"),
    @XmlEnumValue("healthRelatedProfessional")
    HEALTH_RELATED_PROFESSIONAL("healthRelatedProfessional"),
    @XmlEnumValue("administrator")
    ADMINISTRATOR("administrator");
    private final String value;

    FunctionalRoles(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionalRoles fromValue(String v) {
        for (FunctionalRoles c: FunctionalRoles.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
