//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The participation  of an entity in the EHR.  Note that mode
 *         refers to "Mode"  (section 5.5)  in part 3 of the standard,
 *         not "Functional Role Mode" as stated in part 1.
 *       
 * 
 * <p>Java class for FunctionalRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FunctionalRole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="function" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="healthcareFacility" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="mode" type="{http://www.iso.org/iso/search.htm?qt=13606}Mode" minOccurs="0"/>
 *         &lt;element name="performer" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="serviceSetting" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FunctionalRole", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "function",
    "healthcareFacility",
    "mode",
    "performer",
    "serviceSetting"
})
public class FunctionalRole {

    @XmlElement(namespace = "")
    protected CDCV function;
    @XmlElement(namespace = "")
    protected II healthcareFacility;
    @XmlElement(namespace = "")
    protected Mode mode;
    @XmlElement(namespace = "", required = true)
    protected II performer;
    @XmlElement(namespace = "")
    protected CDCV serviceSetting;

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setFunction(CDCV value) {
        this.function = value;
    }

    /**
     * Gets the value of the healthcareFacility property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getHealthcareFacility() {
        return healthcareFacility;
    }

    /**
     * Sets the value of the healthcareFacility property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setHealthcareFacility(II value) {
        this.healthcareFacility = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link Mode }
     *     
     */
    public Mode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mode }
     *     
     */
    public void setMode(Mode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the performer property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getPerformer() {
        return performer;
    }

    /**
     * Sets the value of the performer property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setPerformer(II value) {
        this.performer = value;
    }

    /**
     * Gets the value of the serviceSetting property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getServiceSetting() {
        return serviceSetting;
    }

    /**
     * Sets the value of the serviceSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setServiceSetting(CDCV value) {
        this.serviceSetting = value;
    }

}
