//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Describes the  role of  a  healthcare professional  in  the 
 *         record,  based on  the GPICS  class of the  same name. Note
 *         that the id instances  should refer to the  same identified
 *         individual,   but   might  be   needed  to  establish  that 
 *         individual's identity in different working environments.
 *       
 * 
 * <p>Java class for HealthcareProfessionalRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HealthcareProfessionalRole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="positionOrGrade" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="profession" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="specialty" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="scopingOrganisationId" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HealthcareProfessionalRole", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "id",
    "positionOrGrade",
    "profession",
    "specialty",
    "scopingOrganisationId"
})
public class HealthcareProfessionalRole {

    @XmlElement(namespace = "")
    protected List<II> id;
    @XmlElement(namespace = "")
    protected CDCV positionOrGrade;
    @XmlElement(namespace = "")
    protected CDCV profession;
    @XmlElement(namespace = "")
    protected CDCV specialty;
    @XmlElement(namespace = "")
    protected List<II> scopingOrganisationId;

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the positionOrGrade property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getPositionOrGrade() {
        return positionOrGrade;
    }

    /**
     * Sets the value of the positionOrGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setPositionOrGrade(CDCV value) {
        this.positionOrGrade = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getProfession() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setProfession(CDCV value) {
        this.profession = value;
    }

    /**
     * Gets the value of the specialty property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getSpecialty() {
        return specialty;
    }

    /**
     * Sets the value of the specialty property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setSpecialty(CDCV value) {
        this.specialty = value;
    }

    /**
     * Gets the value of the scopingOrganisationId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scopingOrganisationId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScopingOrganisationId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getScopingOrganisationId() {
        if (scopingOrganisationId == null) {
            scopingOrganisationId = new ArrayList<II>();
        }
        return this.scopingOrganisationId;
    }

}
