//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Reference to an identified healthcare professional, derived 
 *         from GPIC 2.034.
 *       
 * 
 * <p>Java class for IdentifiedHealthcareProfessional complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifiedHealthcareProfessional">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iso.org/iso/search.htm?qt=13606}Person">
 *       &lt;sequence>
 *         &lt;element name="role" type="{http://www.iso.org/iso/search.htm?qt=13606}HealthcareProfessionalRole" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifiedHealthcareProfessional", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "role"
})
public class IdentifiedHealthcareProfessional
    extends Person
{

    @XmlElement(namespace = "")
    protected List<HealthcareProfessionalRole> role;

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HealthcareProfessionalRole }
     * 
     * 
     */
    public List<HealthcareProfessionalRole> getRole() {
        if (role == null) {
            role = new ArrayList<HealthcareProfessionalRole>();
        }
        return this.role;
    }

}
