//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Superclass of all  identified parties  to the record.  Note
 *         that the  type of  id is not  given  in the  printed  class
 *         description  but  is included  in the class diagram on page
 *         47 of the standard.
 *       
 * 
 * <p>Java class for IdentifiedEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifiedEntity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extractId" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="id" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="telecom" type="{uri:iso.org:21090}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifiedEntity", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "extractId",
    "id",
    "telecom"
})
@XmlSeeAlso({
    SoftwareOrDevice.class,
    Organisation.class,
    Person.class
})
public abstract class IdentifiedEntity {

    @XmlElement(namespace = "", required = true)
    protected II extractId;
    @XmlElement(namespace = "")
    protected List<II> id;
    @XmlElement(namespace = "")
    protected List<TEL> telecom;

    /**
     * Gets the value of the extractId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getExtractId() {
        return extractId;
    }

    /**
     * Sets the value of the extractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setExtractId(II value) {
        this.extractId = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the id property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getId() {
        if (id == null) {
            id = new ArrayList<II>();
        }
        return this.id;
    }

    /**
     * Gets the value of the telecom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the telecom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTelecom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEL }
     * 
     * 
     */
    public List<TEL> getTelecom() {
        if (telecom == null) {
            telecom = new ArrayList<TEL>();
        }
        return this.telecom;
    }

}
