//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ItemCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ItemCategory">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="principalValue"/>
 *     &lt;enumeration value="supplementaryDetails"/>
 *     &lt;enumeration value="patientState"/>
 *     &lt;enumeration value="methodDetails"/>
 *     &lt;enumeration value="clinicalReasoning"/>
 *     &lt;enumeration value="protocol"/>
 *     &lt;enumeration value="knowledgeSource"/>
 *     &lt;enumeration value="presentation"/>
 *     &lt;enumeration value="assertionStatus"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ItemCategory", namespace = "http://www.iso.org/iso/search.htm?qt=13606")
@XmlEnum
public enum ItemCategory {

    @XmlEnumValue("principalValue")
    PRINCIPAL_VALUE("principalValue"),
    @XmlEnumValue("supplementaryDetails")
    SUPPLEMENTARY_DETAILS("supplementaryDetails"),
    @XmlEnumValue("patientState")
    PATIENT_STATE("patientState"),
    @XmlEnumValue("methodDetails")
    METHOD_DETAILS("methodDetails"),
    @XmlEnumValue("clinicalReasoning")
    CLINICAL_REASONING("clinicalReasoning"),
    @XmlEnumValue("protocol")
    PROTOCOL("protocol"),
    @XmlEnumValue("knowledgeSource")
    KNOWLEDGE_SOURCE("knowledgeSource"),
    @XmlEnumValue("presentation")
    PRESENTATION("presentation"),
    @XmlEnumValue("assertionStatus")
    ASSERTION_STATUS("assertionStatus");
    private final String value;

    ItemCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ItemCategory fromValue(String v) {
        for (ItemCategory c: ItemCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
