//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Superclass of  Cluster and Element  that enables the former
 *         to include instances of itself.
 *       
 * 
 * <p>Java class for Item complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Item">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iso.org/iso/search.htm?qt=13606}RecordComponent">
 *       &lt;sequence>
 *         &lt;element name="emphasis" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="itemCategory" type="{http://www.iso.org/iso/search.htm?qt=13606}ItemCategory" minOccurs="0"/>
 *         &lt;element name="obsTime" type="{uri:iso.org:21090}IVL_TS" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Item", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "emphasis",
    "itemCategory",
    "obsTime"
})
@XmlSeeAlso({
    Cluster.class,
    Element.class
})
public abstract class Item
    extends RecordComponent
{

    @XmlElement(namespace = "")
    protected CDCV emphasis;
    @XmlElement(namespace = "")
    protected ItemCategory itemCategory;
    @XmlElement(namespace = "")
    protected IVLTS obsTime;

    /**
     * Gets the value of the emphasis property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getEmphasis() {
        return emphasis;
    }

    /**
     * Sets the value of the emphasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setEmphasis(CDCV value) {
        this.emphasis = value;
    }

    /**
     * Gets the value of the itemCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ItemCategory }
     *     
     */
    public ItemCategory getItemCategory() {
        return itemCategory;
    }

    /**
     * Sets the value of the itemCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemCategory }
     *     
     */
    public void setItemCategory(ItemCategory value) {
        this.itemCategory = value;
    }

    /**
     * Gets the value of the obsTime property.
     * 
     * @return
     *     possible object is
     *     {@link IVLTS }
     *     
     */
    public IVLTS getObsTime() {
        return obsTime;
    }

    /**
     * Sets the value of the obsTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link IVLTS }
     *     
     */
    public void setObsTime(IVLTS value) {
        this.obsTime = value;
    }

}
