//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkNature.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LinkNature">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="relatedTo"/>
 *     &lt;enumeration value="confirmedBy"/>
 *     &lt;enumeration value="sameProblem"/>
 *     &lt;enumeration value="samePlan"/>
 *     &lt;enumeration value="relatedDocumentation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LinkNature", namespace = "http://www.iso.org/iso/search.htm?qt=13606")
@XmlEnum
public enum LinkNature {

    @XmlEnumValue("relatedTo")
    RELATED_TO("relatedTo"),
    @XmlEnumValue("confirmedBy")
    CONFIRMED_BY("confirmedBy"),
    @XmlEnumValue("sameProblem")
    SAME_PROBLEM("sameProblem"),
    @XmlEnumValue("samePlan")
    SAME_PLAN("samePlan"),
    @XmlEnumValue("relatedDocumentation")
    RELATED_DOCUMENTATION("relatedDocumentation");
    private final String value;

    LinkNature(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LinkNature fromValue(String v) {
        for (LinkNature c: LinkNature.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
