//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Defines constraints on the sensitivity of Record Components
 *         to which this policy applies.  If only "access" constraints
 *         are given  then  these  are presumed  to apply to  all  EHR
 *         operations. The sensitivity values herein correspond to the
 *         sensitivity values  in the Record Component class  (but are
 *         given as simple  integer types in the standard).  BL is now
 *         boolean.
 *       
 * 
 * <p>Java class for MaxSensitivityConstraints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MaxSensitivityConstraints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="access" type="{http://www.iso.org/iso/search.htm?qt=13606}Sensitivity"/>
 *         &lt;element name="write" type="{http://www.iso.org/iso/search.htm?qt=13606}Sensitivity" minOccurs="0"/>
 *         &lt;element name="modify" type="{http://www.iso.org/iso/search.htm?qt=13606}Sensitivity" minOccurs="0"/>
 *         &lt;element name="communicate" type="{http://www.iso.org/iso/search.htm?qt=13606}Sensitivity" minOccurs="0"/>
 *         &lt;element name="allVersions" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="otherConstraints" type="{uri:iso.org:21090}CD.CV" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MaxSensitivityConstraints", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "access",
    "write",
    "modify",
    "communicate",
    "allVersions",
    "otherConstraints"
})
public class MaxSensitivityConstraints {

    @XmlElement(namespace = "", required = true)
    protected BigInteger access;
    @XmlElement(namespace = "")
    protected BigInteger write;
    @XmlElement(namespace = "")
    protected BigInteger modify;
    @XmlElement(namespace = "")
    protected BigInteger communicate;
    @XmlElement(namespace = "")
    protected boolean allVersions;
    @XmlElement(namespace = "")
    protected List<CDCV> otherConstraints;

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccess(BigInteger value) {
        this.access = value;
    }

    /**
     * Gets the value of the write property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWrite() {
        return write;
    }

    /**
     * Sets the value of the write property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWrite(BigInteger value) {
        this.write = value;
    }

    /**
     * Gets the value of the modify property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getModify() {
        return modify;
    }

    /**
     * Sets the value of the modify property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setModify(BigInteger value) {
        this.modify = value;
    }

    /**
     * Gets the value of the communicate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommunicate() {
        return communicate;
    }

    /**
     * Sets the value of the communicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommunicate(BigInteger value) {
        this.communicate = value;
    }

    /**
     * Gets the value of the allVersions property.
     * 
     */
    public boolean isAllVersions() {
        return allVersions;
    }

    /**
     * Sets the value of the allVersions property.
     * 
     */
    public void setAllVersions(boolean value) {
        this.allVersions = value;
    }

    /**
     * Gets the value of the otherConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDCV }
     * 
     * 
     */
    public List<CDCV> getOtherConstraints() {
        if (otherConstraints == null) {
            otherConstraints = new ArrayList<CDCV>();
        }
        return this.otherConstraints;
    }

}
