//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Mode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="electronicData"/>
 *     &lt;enumeration value="verbal"/>
 *     &lt;enumeration value="dictated"/>
 *     &lt;enumeration value="faceToFace"/>
 *     &lt;enumeration value="telephone"/>
 *     &lt;enumeration value="videoconferencing"/>
 *     &lt;enumeration value="written"/>
 *     &lt;enumeration value="email"/>
 *     &lt;enumeration value="telefax"/>
 *     &lt;enumeration value="handwritten"/>
 *     &lt;enumeration value="typewritten"/>
 *     &lt;enumeration value="physicalPresence"/>
 *     &lt;enumeration value="remotePresence"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Mode", namespace = "http://www.iso.org/iso/search.htm?qt=13606")
@XmlEnum
public enum Mode {

    @XmlEnumValue("electronicData")
    ELECTRONIC_DATA("electronicData"),
    @XmlEnumValue("verbal")
    VERBAL("verbal"),
    @XmlEnumValue("dictated")
    DICTATED("dictated"),
    @XmlEnumValue("faceToFace")
    FACE_TO_FACE("faceToFace"),
    @XmlEnumValue("telephone")
    TELEPHONE("telephone"),
    @XmlEnumValue("videoconferencing")
    VIDEOCONFERENCING("videoconferencing"),
    @XmlEnumValue("written")
    WRITTEN("written"),
    @XmlEnumValue("email")
    EMAIL("email"),
    @XmlEnumValue("telefax")
    TELEFAX("telefax"),
    @XmlEnumValue("handwritten")
    HANDWRITTEN("handwritten"),
    @XmlEnumValue("typewritten")
    TYPEWRITTEN("typewritten"),
    @XmlEnumValue("physicalPresence")
    PHYSICAL_PRESENCE("physicalPresence"),
    @XmlEnumValue("remotePresence")
    REMOTE_PRESENCE("remotePresence");
    private final String value;

    Mode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Mode fromValue(String v) {
        for (Mode c: Mode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
