//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sigaim.siie.iso13606.rm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OBJETOIVLRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLRTO");
    private final static QName _OBJETOCS_QNAME = new QName("uri:iso.org:21090", "OBJETO_CS");
    private final static QName _OBJETOMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_MO");
    private final static QName _OBJETOCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_CO");
    private final static QName _OBJETOHXIT_QNAME = new QName("uri:iso.org:21090", "OBJETO_HXIT");
    private final static QName _OBJETOPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_PQTIME");
    private final static QName _OBJETOQSUINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUINT");
    private final static QName _OBJETOQSSREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSREAL");
    private final static QName _OBJETOQSIRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIRTO");
    private final static QName _OBJETOQSPPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPPQ");
    private final static QName _OBJETOQSSPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSPQTIME");
    private final static QName _OBJETOQSUPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUPQ");
    private final static QName _OBJETOQSPRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPRTO");
    private final static QName _OBJETOIVLWIDTHTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLWIDTHTS");
    private final static QName _OBJETOQSDCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDCO");
    private final static QName _OBJETOIVLLOWTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWTSDATE");
    private final static QName _OBJETOPIVLTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_PIVLTSDATETIME");
    private final static QName _OBJETOQSPPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPPQTIME");
    private final static QName _OBJETOINTNONNEG_QNAME = new QName("uri:iso.org:21090", "OBJETO_INTNONNEG");
    private final static QName _OBJETOQSDTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDTSDATETIME");
    private final static QName _OBJETOQSETPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETPQ");
    private final static QName _OBJETOBL_QNAME = new QName("uri:iso.org:21090", "OBJETO_BL");
    private final static QName _OBJETOQSSPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSPQ");
    private final static QName _OBJETOIVLINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLINT");
    private final static QName _OBJETOQSETREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETREAL");
    private final static QName _OBJETOEIVLTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_EIVLTSDATETIME");
    private final static QName _OBJETOCD_QNAME = new QName("uri:iso.org:21090", "OBJETO_CD");
    private final static QName _OBJETOQSUREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUREAL");
    private final static QName _OBJETOIVLHIGHINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHINT");
    private final static QName _OBJETOTELURL_QNAME = new QName("uri:iso.org:21090", "OBJETO_TELURL");
    private final static QName _OBJETOQSSTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSTSDATE");
    private final static QName _OBJETOQSPINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPINT");
    private final static QName _OBJETOQSIMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIMO");
    private final static QName _OBJETOQSIPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIPQ");
    private final static QName _OBJETOREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_REAL");
    private final static QName _OBJETOIVLPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLPQTIME");
    private final static QName _OBJETOIVLLOWPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWPQTIME");
    private final static QName _OBJETOQSUTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUTSDATE");
    private final static QName _OBJETOQSDTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDTS");
    private final static QName _OBJETOQSDTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDTSDATE");
    private final static QName _OBJETOIVLLOWTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWTSDATETIME");
    private final static QName _OBJETOQSPTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPTSDATETIME");
    private final static QName _OBJETOQSSTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSTSDATETIME");
    private final static QName _OBJETOQSDRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDRTO");
    private final static QName _OBJETOIVLCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLCO");
    private final static QName _OBJETOSC_QNAME = new QName("uri:iso.org:21090", "OBJETO_SC");
    private final static QName _OBJETOINTPOS_QNAME = new QName("uri:iso.org:21090", "OBJETO_INTPOS");
    private final static QName _OBJETOIVLHIGHPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHPQ");
    private final static QName _OBJETOTEL_QNAME = new QName("uri:iso.org:21090", "OBJETO_TEL");
    private final static QName _OBJETOQSDPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDPQTIME");
    private final static QName _OBJETOQSETTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETTSDATE");
    private final static QName _OBJETORTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_RTO");
    private final static QName _OBJETOQSIPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIPQTIME");
    private final static QName _OBJETOPIVLTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_PIVLTSDATE");
    private final static QName _OBJETOQSDREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDREAL");
    private final static QName _OBJETOIVLPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLPQ");
    private final static QName _OBJETOIVLLOWTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWTS");
    private final static QName _OBJETOIVLREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLREAL");
    private final static QName _OBJETOINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_INT");
    private final static QName _OBJETOTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_TSDATETIME");
    private final static QName _OBJETOST_QNAME = new QName("uri:iso.org:21090", "OBJETO_ST");
    private final static QName _OBJETOQSURTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSURTO");
    private final static QName _OBJETOQSICO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSICO");
    private final static QName _OBJETOTSDATETIMEFULL_QNAME = new QName("uri:iso.org:21090", "OBJETO_TSDATETIMEFULL");
    private final static QName _OBJETOQSPMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPMO");
    private final static QName _OBJETOIVLHIGHPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHPQTIME");
    private final static QName _OBJETOIVLLOWMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWMO");
    private final static QName _OBJETOIVLHIGHTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHTSDATE");
    private final static QName _OBJETOIVLHIGHREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHREAL");
    private final static QName _OBJETOQSETPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETPQTIME");
    private final static QName _OBJETOPIVLTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_PIVLTS");
    private final static QName _OBJETOQTY_QNAME = new QName("uri:iso.org:21090", "OBJETO_QTY");
    private final static QName _OBJETOED_QNAME = new QName("uri:iso.org:21090", "OBJETO_ED");
    private final static QName _OBJETOIVLLOWCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWCO");
    private final static QName _OBJETOIVLHIGHTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHTSDATETIME");
    private final static QName _OBJETOSTNT_QNAME = new QName("uri:iso.org:21090", "OBJETO_STNT");
    private final static QName _OBJETOEN_QNAME = new QName("uri:iso.org:21090", "OBJETO_EN");
    private final static QName _OBJETOTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_TS");
    private final static QName _OBJETOQSETINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETINT");
    private final static QName _OBJETOQSPREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPREAL");
    private final static QName _OBJETOTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_TSDATE");
    private final static QName _OBJETOQSPTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPTS");
    private final static QName _OBJETOIVLTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLTSDATETIME");
    private final static QName _OBJETOANY_QNAME = new QName("uri:iso.org:21090", "OBJETO_ANY");
    private final static QName _OBJETOEIVLTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_EIVLTSDATE");
    private final static QName _OBJETOQSETMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETMO");
    private final static QName _OBJETOQSETTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETTSDATETIME");
    private final static QName _OBJETOQSSTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSTS");
    private final static QName _OBJETOIVLHIGHCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHCO");
    private final static QName _OBJETOCDCV_QNAME = new QName("uri:iso.org:21090", "OBJETO_CDCV");
    private final static QName _OBJETOIVLHIGHRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHRTO");
    private final static QName _OBJETOQSUTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUTS");
    private final static QName _OBJETOQSUTSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUTSDATETIME");
    private final static QName _OBJETOQSIINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIINT");
    private final static QName _OBJETOQSIREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSIREAL");
    private final static QName _OBJETOQSSCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSCO");
    private final static QName _OBJETOQSDMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDMO");
    private final static QName _OBJETOQSDINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDINT");
    private final static QName _OBJETOQSUPQTIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUPQTIME");
    private final static QName _OBJETOQSITS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSITS");
    private final static QName _OBJETOADXP_QNAME = new QName("uri:iso.org:21090", "OBJETO_ADXP");
    private final static QName _OBJETOIVLHIGHMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHMO");
    private final static QName _OBJETOEIVLTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_EIVLTS");
    private final static QName _OBJETOQSPCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPCO");
    private final static QName _OBJETOIVLTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLTS");
    private final static QName _OBJETOIVLHIGHTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLHIGHTS");
    private final static QName _OBJETOQSETCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETCO");
    private final static QName _OBJETOQSETRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETRTO");
    private final static QName _OBJETOQSSMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSMO");
    private final static QName _OBJETOENXP_QNAME = new QName("uri:iso.org:21090", "OBJETO_ENXP");
    private final static QName _OBJETOQSDPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSDPQ");
    private final static QName _OBJETOQSSRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSRTO");
    private final static QName _OBJETOIVLLOWRTO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWRTO");
    private final static QName _OBJETOIVLWIDTHCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLWIDTHCO");
    private final static QName _OBJETOXReference_QNAME = new QName("uri:iso.org:21090", "OBJETO_XReference");
    private final static QName _OBJETOIVLLOWPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWPQ");
    private final static QName _EhrExtract_QNAME = new QName("http://www.iso.org/iso/search.htm?qt=13606", "ehrExtract");
    private final static QName _EHRExtract_QNAME = new QName("http://www.iso.org/iso/search.htm?qt=13606", "EHRExtract");
    private final static QName _OBJETOQSETTS_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETTS");
    private final static QName _OBJETOTSDATEFULL_QNAME = new QName("uri:iso.org:21090", "OBJETO_TSDATEFULL");
    private final static QName _OBJETOQSSINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSSINT");
    private final static QName _OBJETOAD_QNAME = new QName("uri:iso.org:21090", "OBJETO_AD");
    private final static QName _OBJETOIVLWIDTHTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLWIDTHTSDATE");
    private final static QName _OBJETOIVLTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLTSDATE");
    private final static QName _OBJETOIVLLOWINT_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWINT");
    private final static QName _OBJETOQSUCO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUCO");
    private final static QName _OBJETOPQ_QNAME = new QName("uri:iso.org:21090", "OBJETO_PQ");
    private final static QName _OBJETOQSETBOUNDEDPIVL_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSETBOUNDEDPIVL");
    private final static QName _OBJETOQSITSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSITSDATE");
    private final static QName _OBJETOEDTEXT_QNAME = new QName("uri:iso.org:21090", "OBJETO_EDTEXT");
    private final static QName _OBJETOPQR_QNAME = new QName("uri:iso.org:21090", "OBJETO_PQR");
    private final static QName _OBJETOIVLLOWREAL_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLLOWREAL");
    private final static QName _OBJETOPQV_QNAME = new QName("uri:iso.org:21090", "OBJETO_PQV");
    private final static QName _OBJETOQSUMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSUMO");
    private final static QName _OBJETOIVLMO_QNAME = new QName("uri:iso.org:21090", "OBJETO_IVLMO");
    private final static QName _OBJETOQSPTSDATE_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSPTSDATE");
    private final static QName _OBJETOQSITSDATETIME_QNAME = new QName("uri:iso.org:21090", "OBJETO_QSITSDATETIME");
    private final static QName _OBJETOII_QNAME = new QName("uri:iso.org:21090", "OBJETO_II");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sigaim.siie.iso13606.rm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EN }
     * 
     */
    public EN createEN() {
        return new EN();
    }

    /**
     * Create an instance of {@link ADXPAL }
     * 
     */
    public ADXPAL createADXPAL() {
        return new ADXPAL();
    }

    /**
     * Create an instance of {@link ADXPSTTYP }
     * 
     */
    public ADXPSTTYP createADXPSTTYP() {
        return new ADXPSTTYP();
    }

    /**
     * Create an instance of {@link AttestationInfo }
     * 
     */
    public AttestationInfo createAttestationInfo() {
        return new AttestationInfo();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link QSPRTO }
     * 
     */
    public QSPRTO createQSPRTO() {
        return new QSPRTO();
    }

    /**
     * Create an instance of {@link QSITSDATETIME }
     * 
     */
    public QSITSDATETIME createQSITSDATETIME() {
        return new QSITSDATETIME();
    }

    /**
     * Create an instance of {@link TSDATE }
     * 
     */
    public TSDATE createTSDATE() {
        return new TSDATE();
    }

    /**
     * Create an instance of {@link Attestation }
     * 
     */
    public Attestation createAttestation() {
        return new Attestation();
    }

    /**
     * Create an instance of {@link II }
     * 
     */
    public II createII() {
        return new II();
    }

    /**
     * Create an instance of {@link ADXPBNN }
     * 
     */
    public ADXPBNN createADXPBNN() {
        return new ADXPBNN();
    }

    /**
     * Create an instance of {@link IVLCO }
     * 
     */
    public IVLCO createIVLCO() {
        return new IVLCO();
    }

    /**
     * Create an instance of {@link IVLINT }
     * 
     */
    public IVLINT createIVLINT() {
        return new IVLINT();
    }

    /**
     * Create an instance of {@link Cluster }
     * 
     */
    public Cluster createCluster() {
        return new Cluster();
    }

    /**
     * Create an instance of {@link IVLHIGHPQTIME }
     * 
     */
    public IVLHIGHPQTIME createIVLHIGHPQTIME() {
        return new IVLHIGHPQTIME();
    }

    /**
     * Create an instance of {@link QSSMO }
     * 
     */
    public QSSMO createQSSMO() {
        return new QSSMO();
    }

    /**
     * Create an instance of {@link ADXPCTY }
     * 
     */
    public ADXPCTY createADXPCTY() {
        return new ADXPCTY();
    }

    /**
     * Create an instance of {@link QSIRTO }
     * 
     */
    public QSIRTO createQSIRTO() {
        return new QSIRTO();
    }

    /**
     * Create an instance of {@link IVLREAL }
     * 
     */
    public IVLREAL createIVLREAL() {
        return new IVLREAL();
    }

    /**
     * Create an instance of {@link ADXPCNT }
     * 
     */
    public ADXPCNT createADXPCNT() {
        return new ADXPCNT();
    }

    /**
     * Create an instance of {@link QSUTS }
     * 
     */
    public QSUTS createQSUTS() {
        return new QSUTS();
    }

    /**
     * Create an instance of {@link QSUREAL }
     * 
     */
    public QSUREAL createQSUREAL() {
        return new QSUREAL();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link ADXPDINSTQ }
     * 
     */
    public ADXPDINSTQ createADXPDINSTQ() {
        return new ADXPDINSTQ();
    }

    /**
     * Create an instance of {@link ExtractCriteria }
     * 
     */
    public ExtractCriteria createExtractCriteria() {
        return new ExtractCriteria();
    }

    /**
     * Create an instance of {@link CS }
     * 
     */
    public CS createCS() {
        return new CS();
    }

    /**
     * Create an instance of {@link CDCV }
     * 
     */
    public CDCV createCDCV() {
        return new CDCV();
    }

    /**
     * Create an instance of {@link EIVLTSDATE }
     * 
     */
    public EIVLTSDATE createEIVLTSDATE() {
        return new EIVLTSDATE();
    }

    /**
     * Create an instance of {@link ADXPDAL }
     * 
     */
    public ADXPDAL createADXPDAL() {
        return new ADXPDAL();
    }

    /**
     * Create an instance of {@link QSPINT }
     * 
     */
    public QSPINT createQSPINT() {
        return new QSPINT();
    }

    /**
     * Create an instance of {@link STNT }
     * 
     */
    public STNT createSTNT() {
        return new STNT();
    }

    /**
     * Create an instance of {@link IVLLOWCO }
     * 
     */
    public IVLLOWCO createIVLLOWCO() {
        return new IVLLOWCO();
    }

    /**
     * Create an instance of {@link ADXPBNR }
     * 
     */
    public ADXPBNR createADXPBNR() {
        return new ADXPBNR();
    }

    /**
     * Create an instance of {@link QSSTSDATETIME }
     * 
     */
    public QSSTSDATETIME createQSSTSDATETIME() {
        return new QSSTSDATETIME();
    }

    /**
     * Create an instance of {@link IVLHIGHINT }
     * 
     */
    public IVLHIGHINT createIVLHIGHINT() {
        return new IVLHIGHINT();
    }

    /**
     * Create an instance of {@link TSDATETIME }
     * 
     */
    public TSDATETIME createTSDATETIME() {
        return new TSDATETIME();
    }

    /**
     * Create an instance of {@link SubjectOfCarePersonIdentification }
     * 
     */
    public SubjectOfCarePersonIdentification createSubjectOfCarePersonIdentification() {
        return new SubjectOfCarePersonIdentification();
    }

    /**
     * Create an instance of {@link ADXPCEN }
     * 
     */
    public ADXPCEN createADXPCEN() {
        return new ADXPCEN();
    }

    /**
     * Create an instance of {@link QSDRTO }
     * 
     */
    public QSDRTO createQSDRTO() {
        return new QSDRTO();
    }

    /**
     * Create an instance of {@link ADXPDINST }
     * 
     */
    public ADXPDINST createADXPDINST() {
        return new ADXPDINST();
    }

    /**
     * Create an instance of {@link REAL }
     * 
     */
    public REAL createREAL() {
        return new REAL();
    }

    /**
     * Create an instance of {@link QSUTSDATETIME }
     * 
     */
    public QSUTSDATETIME createQSUTSDATETIME() {
        return new QSUTSDATETIME();
    }

    /**
     * Create an instance of {@link CD }
     * 
     */
    public CD createCD() {
        return new CD();
    }

    /**
     * Create an instance of {@link QSDPQTIME }
     * 
     */
    public QSDPQTIME createQSDPQTIME() {
        return new QSDPQTIME();
    }

    /**
     * Create an instance of {@link IVLHIGHRTO }
     * 
     */
    public IVLHIGHRTO createIVLHIGHRTO() {
        return new IVLHIGHRTO();
    }

    /**
     * Create an instance of {@link QSSPQ }
     * 
     */
    public QSSPQ createQSSPQ() {
        return new QSSPQ();
    }

    /**
     * Create an instance of {@link PIVLTSDATETIME }
     * 
     */
    public PIVLTSDATETIME createPIVLTSDATETIME() {
        return new PIVLTSDATETIME();
    }

    /**
     * Create an instance of {@link MaxSensitivityConstraints }
     * 
     */
    public MaxSensitivityConstraints createMaxSensitivityConstraints() {
        return new MaxSensitivityConstraints();
    }

    /**
     * Create an instance of {@link ADXP }
     * 
     */
    public ADXP createADXP() {
        return new ADXP();
    }

    /**
     * Create an instance of {@link IdentifiedHealthcareProfessional }
     * 
     */
    public IdentifiedHealthcareProfessional createIdentifiedHealthcareProfessional() {
        return new IdentifiedHealthcareProfessional();
    }

    /**
     * Create an instance of {@link ADXPDMOD }
     * 
     */
    public ADXPDMOD createADXPDMOD() {
        return new ADXPDMOD();
    }

    /**
     * Create an instance of {@link ADXPDMODID }
     * 
     */
    public ADXPDMODID createADXPDMODID() {
        return new ADXPDMODID();
    }

    /**
     * Create an instance of {@link EHRAuditLogExtract }
     * 
     */
    public EHRAuditLogExtract createEHRAuditLogExtract() {
        return new EHRAuditLogExtract();
    }

    /**
     * Create an instance of {@link QSSRTO }
     * 
     */
    public QSSRTO createQSSRTO() {
        return new QSSRTO();
    }

    /**
     * Create an instance of {@link QSSINT }
     * 
     */
    public QSSINT createQSSINT() {
        return new QSSINT();
    }

    /**
     * Create an instance of {@link ADXPSTR }
     * 
     */
    public ADXPSTR createADXPSTR() {
        return new ADXPSTR();
    }

    /**
     * Create an instance of {@link MO }
     * 
     */
    public MO createMO() {
        return new MO();
    }

    /**
     * Create an instance of {@link AuditInfo }
     * 
     */
    public AuditInfo createAuditInfo() {
        return new AuditInfo();
    }

    /**
     * Create an instance of {@link ADXPCAR }
     * 
     */
    public ADXPCAR createADXPCAR() {
        return new ADXPCAR();
    }

    /**
     * Create an instance of {@link QSUPQ }
     * 
     */
    public QSUPQ createQSUPQ() {
        return new QSUPQ();
    }

    /**
     * Create an instance of {@link TS }
     * 
     */
    public TS createTS() {
        return new TS();
    }

    /**
     * Create an instance of {@link QSURTO }
     * 
     */
    public QSURTO createQSURTO() {
        return new QSURTO();
    }

    /**
     * Create an instance of {@link ST }
     * 
     */
    public ST createST() {
        return new ST();
    }

    /**
     * Create an instance of {@link QSDMO }
     * 
     */
    public QSDMO createQSDMO() {
        return new QSDMO();
    }

    /**
     * Create an instance of {@link IVLLOWMO }
     * 
     */
    public IVLLOWMO createIVLLOWMO() {
        return new IVLLOWMO();
    }

    /**
     * Create an instance of {@link FunctionalRole }
     * 
     */
    public FunctionalRole createFunctionalRole() {
        return new FunctionalRole();
    }

    /**
     * Create an instance of {@link AccessPolicy }
     * 
     */
    public AccessPolicy createAccessPolicy() {
        return new AccessPolicy();
    }

    /**
     * Create an instance of {@link IVLHIGHCO }
     * 
     */
    public IVLHIGHCO createIVLHIGHCO() {
        return new IVLHIGHCO();
    }

    /**
     * Create an instance of {@link INTNONNEG }
     * 
     */
    public INTNONNEG createINTNONNEG() {
        return new INTNONNEG();
    }

    /**
     * Create an instance of {@link QSDTSDATETIME }
     * 
     */
    public QSDTSDATETIME createQSDTSDATETIME() {
        return new QSDTSDATETIME();
    }

    /**
     * Create an instance of {@link IVLHIGHPQ }
     * 
     */
    public IVLHIGHPQ createIVLHIGHPQ() {
        return new IVLHIGHPQ();
    }

    /**
     * Create an instance of {@link TSDATEFULL }
     * 
     */
    public TSDATEFULL createTSDATEFULL() {
        return new TSDATEFULL();
    }

    /**
     * Create an instance of {@link QSUINT }
     * 
     */
    public QSUINT createQSUINT() {
        return new QSUINT();
    }

    /**
     * Create an instance of {@link EIVLTS }
     * 
     */
    public EIVLTS createEIVLTS() {
        return new EIVLTS();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link IVLHIGHTSDATE }
     * 
     */
    public IVLHIGHTSDATE createIVLHIGHTSDATE() {
        return new IVLHIGHTSDATE();
    }

    /**
     * Create an instance of {@link Organisation }
     * 
     */
    public Organisation createOrganisation() {
        return new Organisation();
    }

    /**
     * Create an instance of {@link QSDPQ }
     * 
     */
    public QSDPQ createQSDPQ() {
        return new QSDPQ();
    }

    /**
     * Create an instance of {@link IVLLOWRTO }
     * 
     */
    public IVLLOWRTO createIVLLOWRTO() {
        return new IVLLOWRTO();
    }

    /**
     * Create an instance of {@link AD }
     * 
     */
    public AD createAD() {
        return new AD();
    }

    /**
     * Create an instance of {@link QSPPQTIME }
     * 
     */
    public QSPPQTIME createQSPPQTIME() {
        return new QSPPQTIME();
    }

    /**
     * Create an instance of {@link ADXPPOB }
     * 
     */
    public ADXPPOB createADXPPOB() {
        return new ADXPPOB();
    }

    /**
     * Create an instance of {@link QSITSDATE }
     * 
     */
    public QSITSDATE createQSITSDATE() {
        return new QSITSDATE();
    }

    /**
     * Create an instance of {@link ADXPINT }
     * 
     */
    public ADXPINT createADXPINT() {
        return new ADXPINT();
    }

    /**
     * Create an instance of {@link SC }
     * 
     */
    public SC createSC() {
        return new SC();
    }

    /**
     * Create an instance of {@link TELURL }
     * 
     */
    public TELURL createTELURL() {
        return new TELURL();
    }

    /**
     * Create an instance of {@link IVLRTO }
     * 
     */
    public IVLRTO createIVLRTO() {
        return new IVLRTO();
    }

    /**
     * Create an instance of {@link IVLLOWPQTIME }
     * 
     */
    public IVLLOWPQTIME createIVLLOWPQTIME() {
        return new IVLLOWPQTIME();
    }

    /**
     * Create an instance of {@link EHRExtract }
     * 
     */
    public EHRExtract createEHRExtract() {
        return new EHRExtract();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link EDTEXT }
     * 
     */
    public EDTEXT createEDTEXT() {
        return new EDTEXT();
    }

    /**
     * Create an instance of {@link PQV }
     * 
     */
    public PQV createPQV() {
        return new PQV();
    }

    /**
     * Create an instance of {@link QSDTSDATE }
     * 
     */
    public QSDTSDATE createQSDTSDATE() {
        return new QSDTSDATE();
    }

    /**
     * Create an instance of {@link IVLWIDTHTS }
     * 
     */
    public IVLWIDTHTS createIVLWIDTHTS() {
        return new IVLWIDTHTS();
    }

    /**
     * Create an instance of {@link QSIREAL }
     * 
     */
    public QSIREAL createQSIREAL() {
        return new QSIREAL();
    }

    /**
     * Create an instance of {@link TEL }
     * 
     */
    public TEL createTEL() {
        return new TEL();
    }

    /**
     * Create an instance of {@link AuditLogConstraints }
     * 
     */
    public AuditLogConstraints createAuditLogConstraints() {
        return new AuditLogConstraints();
    }

    /**
     * Create an instance of {@link TSDATETIMEFULL }
     * 
     */
    public TSDATETIMEFULL createTSDATETIMEFULL() {
        return new TSDATETIMEFULL();
    }

    /**
     * Create an instance of {@link HealthcareProfessionalRole }
     * 
     */
    public HealthcareProfessionalRole createHealthcareProfessionalRole() {
        return new HealthcareProfessionalRole();
    }

    /**
     * Create an instance of {@link IVLPQTIME }
     * 
     */
    public IVLPQTIME createIVLPQTIME() {
        return new IVLPQTIME();
    }

    /**
     * Create an instance of {@link PQR }
     * 
     */
    public PQR createPQR() {
        return new PQR();
    }

    /**
     * Create an instance of {@link QSUMO }
     * 
     */
    public QSUMO createQSUMO() {
        return new QSUMO();
    }

    /**
     * Create an instance of {@link QSSCO }
     * 
     */
    public QSSCO createQSSCO() {
        return new QSSCO();
    }

    /**
     * Create an instance of {@link IVLTSDATE }
     * 
     */
    public IVLTSDATE createIVLTSDATE() {
        return new IVLTSDATE();
    }

    /**
     * Create an instance of {@link ADXPBNS }
     * 
     */
    public ADXPBNS createADXPBNS() {
        return new ADXPBNS();
    }

    /**
     * Create an instance of {@link ADXPZIP }
     * 
     */
    public ADXPZIP createADXPZIP() {
        return new ADXPZIP();
    }

    /**
     * Create an instance of {@link QSDTS }
     * 
     */
    public QSDTS createQSDTS() {
        return new QSDTS();
    }

    /**
     * Create an instance of {@link PQ }
     * 
     */
    public PQ createPQ() {
        return new PQ();
    }

    /**
     * Create an instance of {@link QSPTS }
     * 
     */
    public QSPTS createQSPTS() {
        return new QSPTS();
    }

    /**
     * Create an instance of {@link QSSTS }
     * 
     */
    public QSSTS createQSSTS() {
        return new QSSTS();
    }

    /**
     * Create an instance of {@link IVLTS }
     * 
     */
    public IVLTS createIVLTS() {
        return new IVLTS();
    }

    /**
     * Create an instance of {@link SoftwareOrDevice }
     * 
     */
    public SoftwareOrDevice createSoftwareOrDevice() {
        return new SoftwareOrDevice();
    }

    /**
     * Create an instance of {@link IVLLOWTSDATETIME }
     * 
     */
    public IVLLOWTSDATETIME createIVLLOWTSDATETIME() {
        return new IVLLOWTSDATETIME();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link PQTIME }
     * 
     */
    public PQTIME createPQTIME() {
        return new PQTIME();
    }

    /**
     * Create an instance of {@link IVLLOWTS }
     * 
     */
    public IVLLOWTS createIVLLOWTS() {
        return new IVLLOWTS();
    }

    /**
     * Create an instance of {@link QSETBOUNDEDPIVL }
     * 
     */
    public QSETBOUNDEDPIVL createQSETBOUNDEDPIVL() {
        return new QSETBOUNDEDPIVL();
    }

    /**
     * Create an instance of {@link QSSPQTIME }
     * 
     */
    public QSSPQTIME createQSSPQTIME() {
        return new QSSPQTIME();
    }

    /**
     * Create an instance of {@link ADXPUNIT }
     * 
     */
    public ADXPUNIT createADXPUNIT() {
        return new ADXPUNIT();
    }

    /**
     * Create an instance of {@link RelatedParty }
     * 
     */
    public RelatedParty createRelatedParty() {
        return new RelatedParty();
    }

    /**
     * Create an instance of {@link IVLMO }
     * 
     */
    public IVLMO createIVLMO() {
        return new IVLMO();
    }

    /**
     * Create an instance of {@link EHRAuditLogEntry }
     * 
     */
    public EHRAuditLogEntry createEHRAuditLogEntry() {
        return new EHRAuditLogEntry();
    }

    /**
     * Create an instance of {@link XReference }
     * 
     */
    public XReference createXReference() {
        return new XReference();
    }

    /**
     * Create an instance of {@link QSPCO }
     * 
     */
    public QSPCO createQSPCO() {
        return new QSPCO();
    }

    /**
     * Create an instance of {@link CO }
     * 
     */
    public CO createCO() {
        return new CO();
    }

    /**
     * Create an instance of {@link IVLHIGHTSDATETIME }
     * 
     */
    public IVLHIGHTSDATETIME createIVLHIGHTSDATETIME() {
        return new IVLHIGHTSDATETIME();
    }

    /**
     * Create an instance of {@link ADXPDINSTA }
     * 
     */
    public ADXPDINSTA createADXPDINSTA() {
        return new ADXPDINSTA();
    }

    /**
     * Create an instance of {@link DemographicExtract }
     * 
     */
    public DemographicExtract createDemographicExtract() {
        return new DemographicExtract();
    }

    /**
     * Create an instance of {@link IVLLOWTSDATE }
     * 
     */
    public IVLLOWTSDATE createIVLLOWTSDATE() {
        return new IVLLOWTSDATE();
    }

    /**
     * Create an instance of {@link BL }
     * 
     */
    public BL createBL() {
        return new BL();
    }

    /**
     * Create an instance of {@link ENXP }
     * 
     */
    public ENXP createENXP() {
        return new ENXP();
    }

    /**
     * Create an instance of {@link ADXPSTB }
     * 
     */
    public ADXPSTB createADXPSTB() {
        return new ADXPSTB();
    }

    /**
     * Create an instance of {@link QSDCO }
     * 
     */
    public QSDCO createQSDCO() {
        return new QSDCO();
    }

    /**
     * Create an instance of {@link Composition }
     * 
     */
    public Composition createComposition() {
        return new Composition();
    }

    /**
     * Create an instance of {@link ADXPDIR }
     * 
     */
    public ADXPDIR createADXPDIR() {
        return new ADXPDIR();
    }

    /**
     * Create an instance of {@link QSPTSDATE }
     * 
     */
    public QSPTSDATE createQSPTSDATE() {
        return new QSPTSDATE();
    }

    /**
     * Create an instance of {@link EIVLTSDATETIME }
     * 
     */
    public EIVLTSDATETIME createEIVLTSDATETIME() {
        return new EIVLTSDATETIME();
    }

    /**
     * Create an instance of {@link QSPREAL }
     * 
     */
    public QSPREAL createQSPREAL() {
        return new QSPREAL();
    }

    /**
     * Create an instance of {@link ADXPUNID }
     * 
     */
    public ADXPUNID createADXPUNID() {
        return new ADXPUNID();
    }

    /**
     * Create an instance of {@link ADXPSTA }
     * 
     */
    public ADXPSTA createADXPSTA() {
        return new ADXPSTA();
    }

    /**
     * Create an instance of {@link IVLPQ }
     * 
     */
    public IVLPQ createIVLPQ() {
        return new IVLPQ();
    }

    /**
     * Create an instance of {@link IVLHIGHMO }
     * 
     */
    public IVLHIGHMO createIVLHIGHMO() {
        return new IVLHIGHMO();
    }

    /**
     * Create an instance of {@link QSDINT }
     * 
     */
    public QSDINT createQSDINT() {
        return new QSDINT();
    }

    /**
     * Create an instance of {@link ADXPADL }
     * 
     */
    public ADXPADL createADXPADL() {
        return new ADXPADL();
    }

    /**
     * Create an instance of {@link QSIPQ }
     * 
     */
    public QSIPQ createQSIPQ() {
        return new QSIPQ();
    }

    /**
     * Create an instance of {@link INTPOS }
     * 
     */
    public INTPOS createINTPOS() {
        return new INTPOS();
    }

    /**
     * Create an instance of {@link QSPMO }
     * 
     */
    public QSPMO createQSPMO() {
        return new QSPMO();
    }

    /**
     * Create an instance of {@link PIVLTS }
     * 
     */
    public PIVLTS createPIVLTS() {
        return new PIVLTS();
    }

    /**
     * Create an instance of {@link QSUCO }
     * 
     */
    public QSUCO createQSUCO() {
        return new QSUCO();
    }

    /**
     * Create an instance of {@link QSDREAL }
     * 
     */
    public QSDREAL createQSDREAL() {
        return new QSDREAL();
    }

    /**
     * Create an instance of {@link QSUPQTIME }
     * 
     */
    public QSUPQTIME createQSUPQTIME() {
        return new QSUPQTIME();
    }

    /**
     * Create an instance of {@link IVLWIDTHCO }
     * 
     */
    public IVLWIDTHCO createIVLWIDTHCO() {
        return new IVLWIDTHCO();
    }

    /**
     * Create an instance of {@link QSSTSDATE }
     * 
     */
    public QSSTSDATE createQSSTSDATE() {
        return new QSSTSDATE();
    }

    /**
     * Create an instance of {@link QSSREAL }
     * 
     */
    public QSSREAL createQSSREAL() {
        return new QSSREAL();
    }

    /**
     * Create an instance of {@link QSUTSDATE }
     * 
     */
    public QSUTSDATE createQSUTSDATE() {
        return new QSUTSDATE();
    }

    /**
     * Create an instance of {@link QSIINT }
     * 
     */
    public QSIINT createQSIINT() {
        return new QSIINT();
    }

    /**
     * Create an instance of {@link INT }
     * 
     */
    public INT createINT() {
        return new INT();
    }

    /**
     * Create an instance of {@link IVLTSDATETIME }
     * 
     */
    public IVLTSDATETIME createIVLTSDATETIME() {
        return new IVLTSDATETIME();
    }

    /**
     * Create an instance of {@link QSITS }
     * 
     */
    public QSITS createQSITS() {
        return new QSITS();
    }

    /**
     * Create an instance of {@link QSICO }
     * 
     */
    public QSICO createQSICO() {
        return new QSICO();
    }

    /**
     * Create an instance of {@link ANY }
     * 
     */
    public ANY createANY() {
        return new ANY();
    }

    /**
     * Create an instance of {@link QSPPQ }
     * 
     */
    public QSPPQ createQSPPQ() {
        return new QSPPQ();
    }

    /**
     * Create an instance of {@link IVLHIGHREAL }
     * 
     */
    public IVLHIGHREAL createIVLHIGHREAL() {
        return new IVLHIGHREAL();
    }

    /**
     * Create an instance of {@link Target }
     * 
     */
    public Target createTarget() {
        return new Target();
    }

    /**
     * Create an instance of {@link ADXPCPA }
     * 
     */
    public ADXPCPA createADXPCPA() {
        return new ADXPCPA();
    }

    /**
     * Create an instance of {@link IVLHIGHTS }
     * 
     */
    public IVLHIGHTS createIVLHIGHTS() {
        return new IVLHIGHTS();
    }

    /**
     * Create an instance of {@link IVLLOWINT }
     * 
     */
    public IVLLOWINT createIVLLOWINT() {
        return new IVLLOWINT();
    }

    /**
     * Create an instance of {@link PIVLTSDATE }
     * 
     */
    public PIVLTSDATE createPIVLTSDATE() {
        return new PIVLTSDATE();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link QSIPQTIME }
     * 
     */
    public QSIPQTIME createQSIPQTIME() {
        return new QSIPQTIME();
    }

    /**
     * Create an instance of {@link ADXPSAL }
     * 
     */
    public ADXPSAL createADXPSAL() {
        return new ADXPSAL();
    }

    /**
     * Create an instance of {@link RTO }
     * 
     */
    public RTO createRTO() {
        return new RTO();
    }

    /**
     * Create an instance of {@link ED }
     * 
     */
    public ED createED() {
        return new ED();
    }

    /**
     * Create an instance of {@link IVLLOWPQ }
     * 
     */
    public IVLLOWPQ createIVLLOWPQ() {
        return new IVLLOWPQ();
    }

    /**
     * Create an instance of {@link QSIMO }
     * 
     */
    public QSIMO createQSIMO() {
        return new QSIMO();
    }

    /**
     * Create an instance of {@link IVLLOWREAL }
     * 
     */
    public IVLLOWREAL createIVLLOWREAL() {
        return new IVLLOWREAL();
    }

    /**
     * Create an instance of {@link ADXPPRE }
     * 
     */
    public ADXPPRE createADXPPRE() {
        return new ADXPPRE();
    }

    /**
     * Create an instance of {@link IVLWIDTHTSDATE }
     * 
     */
    public IVLWIDTHTSDATE createIVLWIDTHTSDATE() {
        return new IVLWIDTHTSDATE();
    }

    /**
     * Create an instance of {@link QSPTSDATETIME }
     * 
     */
    public QSPTSDATETIME createQSPTSDATETIME() {
        return new QSPTSDATETIME();
    }

    /**
     * Create an instance of {@link ADXPBR }
     * 
     */
    public ADXPBR createADXPBR() {
        return new ADXPBR();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLRTO")
    public JAXBElement<IVLRTO> createOBJETOIVLRTO(IVLRTO value) {
        return new JAXBElement<IVLRTO>(_OBJETOIVLRTO_QNAME, IVLRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_CS")
    public JAXBElement<CS> createOBJETOCS(CS value) {
        return new JAXBElement<CS>(_OBJETOCS_QNAME, CS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_MO")
    public JAXBElement<MO> createOBJETOMO(MO value) {
        return new JAXBElement<MO>(_OBJETOMO_QNAME, MO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_CO")
    public JAXBElement<CO> createOBJETOCO(CO value) {
        return new JAXBElement<CO>(_OBJETOCO_QNAME, CO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HXIT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_HXIT")
    public JAXBElement<HXIT> createOBJETOHXIT(HXIT value) {
        return new JAXBElement<HXIT>(_OBJETOHXIT_QNAME, HXIT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PQTIME")
    public JAXBElement<PQTIME> createOBJETOPQTIME(PQTIME value) {
        return new JAXBElement<PQTIME>(_OBJETOPQTIME_QNAME, PQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUINT")
    public JAXBElement<QSUINT> createOBJETOQSUINT(QSUINT value) {
        return new JAXBElement<QSUINT>(_OBJETOQSUINT_QNAME, QSUINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSREAL")
    public JAXBElement<QSSREAL> createOBJETOQSSREAL(QSSREAL value) {
        return new JAXBElement<QSSREAL>(_OBJETOQSSREAL_QNAME, QSSREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIRTO")
    public JAXBElement<QSIRTO> createOBJETOQSIRTO(QSIRTO value) {
        return new JAXBElement<QSIRTO>(_OBJETOQSIRTO_QNAME, QSIRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPPQ")
    public JAXBElement<QSPPQ> createOBJETOQSPPQ(QSPPQ value) {
        return new JAXBElement<QSPPQ>(_OBJETOQSPPQ_QNAME, QSPPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSPQTIME")
    public JAXBElement<QSSPQTIME> createOBJETOQSSPQTIME(QSSPQTIME value) {
        return new JAXBElement<QSSPQTIME>(_OBJETOQSSPQTIME_QNAME, QSSPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUPQ")
    public JAXBElement<QSUPQ> createOBJETOQSUPQ(QSUPQ value) {
        return new JAXBElement<QSUPQ>(_OBJETOQSUPQ_QNAME, QSUPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPRTO")
    public JAXBElement<QSPRTO> createOBJETOQSPRTO(QSPRTO value) {
        return new JAXBElement<QSPRTO>(_OBJETOQSPRTO_QNAME, QSPRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLWIDTHTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLWIDTHTS")
    public JAXBElement<IVLWIDTHTS> createOBJETOIVLWIDTHTS(IVLWIDTHTS value) {
        return new JAXBElement<IVLWIDTHTS>(_OBJETOIVLWIDTHTS_QNAME, IVLWIDTHTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDCO")
    public JAXBElement<QSDCO> createOBJETOQSDCO(QSDCO value) {
        return new JAXBElement<QSDCO>(_OBJETOQSDCO_QNAME, QSDCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWTSDATE")
    public JAXBElement<IVLLOWTSDATE> createOBJETOIVLLOWTSDATE(IVLLOWTSDATE value) {
        return new JAXBElement<IVLLOWTSDATE>(_OBJETOIVLLOWTSDATE_QNAME, IVLLOWTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PIVLTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PIVLTSDATETIME")
    public JAXBElement<PIVLTSDATETIME> createOBJETOPIVLTSDATETIME(PIVLTSDATETIME value) {
        return new JAXBElement<PIVLTSDATETIME>(_OBJETOPIVLTSDATETIME_QNAME, PIVLTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPPQTIME")
    public JAXBElement<QSPPQTIME> createOBJETOQSPPQTIME(QSPPQTIME value) {
        return new JAXBElement<QSPPQTIME>(_OBJETOQSPPQTIME_QNAME, QSPPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INTNONNEG }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_INTNONNEG")
    public JAXBElement<INTNONNEG> createOBJETOINTNONNEG(INTNONNEG value) {
        return new JAXBElement<INTNONNEG>(_OBJETOINTNONNEG_QNAME, INTNONNEG.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDTSDATETIME")
    public JAXBElement<QSDTSDATETIME> createOBJETOQSDTSDATETIME(QSDTSDATETIME value) {
        return new JAXBElement<QSDTSDATETIME>(_OBJETOQSDTSDATETIME_QNAME, QSDTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETPQ")
    public JAXBElement<QSETPQ> createOBJETOQSETPQ(QSETPQ value) {
        return new JAXBElement<QSETPQ>(_OBJETOQSETPQ_QNAME, QSETPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_BL")
    public JAXBElement<BL> createOBJETOBL(BL value) {
        return new JAXBElement<BL>(_OBJETOBL_QNAME, BL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSPQ")
    public JAXBElement<QSSPQ> createOBJETOQSSPQ(QSSPQ value) {
        return new JAXBElement<QSSPQ>(_OBJETOQSSPQ_QNAME, QSSPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLINT")
    public JAXBElement<IVLINT> createOBJETOIVLINT(IVLINT value) {
        return new JAXBElement<IVLINT>(_OBJETOIVLINT_QNAME, IVLINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETREAL")
    public JAXBElement<QSETREAL> createOBJETOQSETREAL(QSETREAL value) {
        return new JAXBElement<QSETREAL>(_OBJETOQSETREAL_QNAME, QSETREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EIVLTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_EIVLTSDATETIME")
    public JAXBElement<EIVLTSDATETIME> createOBJETOEIVLTSDATETIME(EIVLTSDATETIME value) {
        return new JAXBElement<EIVLTSDATETIME>(_OBJETOEIVLTSDATETIME_QNAME, EIVLTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_CD")
    public JAXBElement<CD> createOBJETOCD(CD value) {
        return new JAXBElement<CD>(_OBJETOCD_QNAME, CD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUREAL")
    public JAXBElement<QSUREAL> createOBJETOQSUREAL(QSUREAL value) {
        return new JAXBElement<QSUREAL>(_OBJETOQSUREAL_QNAME, QSUREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHINT")
    public JAXBElement<IVLHIGHINT> createOBJETOIVLHIGHINT(IVLHIGHINT value) {
        return new JAXBElement<IVLHIGHINT>(_OBJETOIVLHIGHINT_QNAME, IVLHIGHINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TELURL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TELURL")
    public JAXBElement<TELURL> createOBJETOTELURL(TELURL value) {
        return new JAXBElement<TELURL>(_OBJETOTELURL_QNAME, TELURL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSTSDATE")
    public JAXBElement<QSSTSDATE> createOBJETOQSSTSDATE(QSSTSDATE value) {
        return new JAXBElement<QSSTSDATE>(_OBJETOQSSTSDATE_QNAME, QSSTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPINT")
    public JAXBElement<QSPINT> createOBJETOQSPINT(QSPINT value) {
        return new JAXBElement<QSPINT>(_OBJETOQSPINT_QNAME, QSPINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIMO")
    public JAXBElement<QSIMO> createOBJETOQSIMO(QSIMO value) {
        return new JAXBElement<QSIMO>(_OBJETOQSIMO_QNAME, QSIMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIPQ")
    public JAXBElement<QSIPQ> createOBJETOQSIPQ(QSIPQ value) {
        return new JAXBElement<QSIPQ>(_OBJETOQSIPQ_QNAME, QSIPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link REAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_REAL")
    public JAXBElement<REAL> createOBJETOREAL(REAL value) {
        return new JAXBElement<REAL>(_OBJETOREAL_QNAME, REAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLPQTIME")
    public JAXBElement<IVLPQTIME> createOBJETOIVLPQTIME(IVLPQTIME value) {
        return new JAXBElement<IVLPQTIME>(_OBJETOIVLPQTIME_QNAME, IVLPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWPQTIME")
    public JAXBElement<IVLLOWPQTIME> createOBJETOIVLLOWPQTIME(IVLLOWPQTIME value) {
        return new JAXBElement<IVLLOWPQTIME>(_OBJETOIVLLOWPQTIME_QNAME, IVLLOWPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUTSDATE")
    public JAXBElement<QSUTSDATE> createOBJETOQSUTSDATE(QSUTSDATE value) {
        return new JAXBElement<QSUTSDATE>(_OBJETOQSUTSDATE_QNAME, QSUTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDTS")
    public JAXBElement<QSDTS> createOBJETOQSDTS(QSDTS value) {
        return new JAXBElement<QSDTS>(_OBJETOQSDTS_QNAME, QSDTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDTSDATE")
    public JAXBElement<QSDTSDATE> createOBJETOQSDTSDATE(QSDTSDATE value) {
        return new JAXBElement<QSDTSDATE>(_OBJETOQSDTSDATE_QNAME, QSDTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWTSDATETIME")
    public JAXBElement<IVLLOWTSDATETIME> createOBJETOIVLLOWTSDATETIME(IVLLOWTSDATETIME value) {
        return new JAXBElement<IVLLOWTSDATETIME>(_OBJETOIVLLOWTSDATETIME_QNAME, IVLLOWTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPTSDATETIME")
    public JAXBElement<QSPTSDATETIME> createOBJETOQSPTSDATETIME(QSPTSDATETIME value) {
        return new JAXBElement<QSPTSDATETIME>(_OBJETOQSPTSDATETIME_QNAME, QSPTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSTSDATETIME")
    public JAXBElement<QSSTSDATETIME> createOBJETOQSSTSDATETIME(QSSTSDATETIME value) {
        return new JAXBElement<QSSTSDATETIME>(_OBJETOQSSTSDATETIME_QNAME, QSSTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDRTO")
    public JAXBElement<QSDRTO> createOBJETOQSDRTO(QSDRTO value) {
        return new JAXBElement<QSDRTO>(_OBJETOQSDRTO_QNAME, QSDRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLCO")
    public JAXBElement<IVLCO> createOBJETOIVLCO(IVLCO value) {
        return new JAXBElement<IVLCO>(_OBJETOIVLCO_QNAME, IVLCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_SC")
    public JAXBElement<SC> createOBJETOSC(SC value) {
        return new JAXBElement<SC>(_OBJETOSC_QNAME, SC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INTPOS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_INTPOS")
    public JAXBElement<INTPOS> createOBJETOINTPOS(INTPOS value) {
        return new JAXBElement<INTPOS>(_OBJETOINTPOS_QNAME, INTPOS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHPQ")
    public JAXBElement<IVLHIGHPQ> createOBJETOIVLHIGHPQ(IVLHIGHPQ value) {
        return new JAXBElement<IVLHIGHPQ>(_OBJETOIVLHIGHPQ_QNAME, IVLHIGHPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TEL")
    public JAXBElement<TEL> createOBJETOTEL(TEL value) {
        return new JAXBElement<TEL>(_OBJETOTEL_QNAME, TEL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDPQTIME")
    public JAXBElement<QSDPQTIME> createOBJETOQSDPQTIME(QSDPQTIME value) {
        return new JAXBElement<QSDPQTIME>(_OBJETOQSDPQTIME_QNAME, QSDPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETTSDATE")
    public JAXBElement<QSETTSDATE> createOBJETOQSETTSDATE(QSETTSDATE value) {
        return new JAXBElement<QSETTSDATE>(_OBJETOQSETTSDATE_QNAME, QSETTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_RTO")
    public JAXBElement<RTO> createOBJETORTO(RTO value) {
        return new JAXBElement<RTO>(_OBJETORTO_QNAME, RTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIPQTIME")
    public JAXBElement<QSIPQTIME> createOBJETOQSIPQTIME(QSIPQTIME value) {
        return new JAXBElement<QSIPQTIME>(_OBJETOQSIPQTIME_QNAME, QSIPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PIVLTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PIVLTSDATE")
    public JAXBElement<PIVLTSDATE> createOBJETOPIVLTSDATE(PIVLTSDATE value) {
        return new JAXBElement<PIVLTSDATE>(_OBJETOPIVLTSDATE_QNAME, PIVLTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDREAL")
    public JAXBElement<QSDREAL> createOBJETOQSDREAL(QSDREAL value) {
        return new JAXBElement<QSDREAL>(_OBJETOQSDREAL_QNAME, QSDREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLPQ")
    public JAXBElement<IVLPQ> createOBJETOIVLPQ(IVLPQ value) {
        return new JAXBElement<IVLPQ>(_OBJETOIVLPQ_QNAME, IVLPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWTS")
    public JAXBElement<IVLLOWTS> createOBJETOIVLLOWTS(IVLLOWTS value) {
        return new JAXBElement<IVLLOWTS>(_OBJETOIVLLOWTS_QNAME, IVLLOWTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLREAL")
    public JAXBElement<IVLREAL> createOBJETOIVLREAL(IVLREAL value) {
        return new JAXBElement<IVLREAL>(_OBJETOIVLREAL_QNAME, IVLREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link INT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_INT")
    public JAXBElement<INT> createOBJETOINT(INT value) {
        return new JAXBElement<INT>(_OBJETOINT_QNAME, INT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TSDATETIME")
    public JAXBElement<TSDATETIME> createOBJETOTSDATETIME(TSDATETIME value) {
        return new JAXBElement<TSDATETIME>(_OBJETOTSDATETIME_QNAME, TSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ST }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_ST")
    public JAXBElement<ST> createOBJETOST(ST value) {
        return new JAXBElement<ST>(_OBJETOST_QNAME, ST.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSURTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSURTO")
    public JAXBElement<QSURTO> createOBJETOQSURTO(QSURTO value) {
        return new JAXBElement<QSURTO>(_OBJETOQSURTO_QNAME, QSURTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSICO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSICO")
    public JAXBElement<QSICO> createOBJETOQSICO(QSICO value) {
        return new JAXBElement<QSICO>(_OBJETOQSICO_QNAME, QSICO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSDATETIMEFULL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TSDATETIMEFULL")
    public JAXBElement<TSDATETIMEFULL> createOBJETOTSDATETIMEFULL(TSDATETIMEFULL value) {
        return new JAXBElement<TSDATETIMEFULL>(_OBJETOTSDATETIMEFULL_QNAME, TSDATETIMEFULL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPMO")
    public JAXBElement<QSPMO> createOBJETOQSPMO(QSPMO value) {
        return new JAXBElement<QSPMO>(_OBJETOQSPMO_QNAME, QSPMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHPQTIME")
    public JAXBElement<IVLHIGHPQTIME> createOBJETOIVLHIGHPQTIME(IVLHIGHPQTIME value) {
        return new JAXBElement<IVLHIGHPQTIME>(_OBJETOIVLHIGHPQTIME_QNAME, IVLHIGHPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWMO")
    public JAXBElement<IVLLOWMO> createOBJETOIVLLOWMO(IVLLOWMO value) {
        return new JAXBElement<IVLLOWMO>(_OBJETOIVLLOWMO_QNAME, IVLLOWMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHTSDATE")
    public JAXBElement<IVLHIGHTSDATE> createOBJETOIVLHIGHTSDATE(IVLHIGHTSDATE value) {
        return new JAXBElement<IVLHIGHTSDATE>(_OBJETOIVLHIGHTSDATE_QNAME, IVLHIGHTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHREAL")
    public JAXBElement<IVLHIGHREAL> createOBJETOIVLHIGHREAL(IVLHIGHREAL value) {
        return new JAXBElement<IVLHIGHREAL>(_OBJETOIVLHIGHREAL_QNAME, IVLHIGHREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETPQTIME")
    public JAXBElement<QSETPQTIME> createOBJETOQSETPQTIME(QSETPQTIME value) {
        return new JAXBElement<QSETPQTIME>(_OBJETOQSETPQTIME_QNAME, QSETPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PIVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PIVLTS")
    public JAXBElement<PIVLTS> createOBJETOPIVLTS(PIVLTS value) {
        return new JAXBElement<PIVLTS>(_OBJETOPIVLTS_QNAME, PIVLTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QTY }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QTY")
    public JAXBElement<QTY> createOBJETOQTY(QTY value) {
        return new JAXBElement<QTY>(_OBJETOQTY_QNAME, QTY.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ED }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_ED")
    public JAXBElement<ED> createOBJETOED(ED value) {
        return new JAXBElement<ED>(_OBJETOED_QNAME, ED.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWCO")
    public JAXBElement<IVLLOWCO> createOBJETOIVLLOWCO(IVLLOWCO value) {
        return new JAXBElement<IVLLOWCO>(_OBJETOIVLLOWCO_QNAME, IVLLOWCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHTSDATETIME")
    public JAXBElement<IVLHIGHTSDATETIME> createOBJETOIVLHIGHTSDATETIME(IVLHIGHTSDATETIME value) {
        return new JAXBElement<IVLHIGHTSDATETIME>(_OBJETOIVLHIGHTSDATETIME_QNAME, IVLHIGHTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link STNT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_STNT")
    public JAXBElement<STNT> createOBJETOSTNT(STNT value) {
        return new JAXBElement<STNT>(_OBJETOSTNT_QNAME, STNT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_EN")
    public JAXBElement<EN> createOBJETOEN(EN value) {
        return new JAXBElement<EN>(_OBJETOEN_QNAME, EN.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TS")
    public JAXBElement<TS> createOBJETOTS(TS value) {
        return new JAXBElement<TS>(_OBJETOTS_QNAME, TS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETINT")
    public JAXBElement<QSETINT> createOBJETOQSETINT(QSETINT value) {
        return new JAXBElement<QSETINT>(_OBJETOQSETINT_QNAME, QSETINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPREAL")
    public JAXBElement<QSPREAL> createOBJETOQSPREAL(QSPREAL value) {
        return new JAXBElement<QSPREAL>(_OBJETOQSPREAL_QNAME, QSPREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TSDATE")
    public JAXBElement<TSDATE> createOBJETOTSDATE(TSDATE value) {
        return new JAXBElement<TSDATE>(_OBJETOTSDATE_QNAME, TSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPTS")
    public JAXBElement<QSPTS> createOBJETOQSPTS(QSPTS value) {
        return new JAXBElement<QSPTS>(_OBJETOQSPTS_QNAME, QSPTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLTSDATETIME")
    public JAXBElement<IVLTSDATETIME> createOBJETOIVLTSDATETIME(IVLTSDATETIME value) {
        return new JAXBElement<IVLTSDATETIME>(_OBJETOIVLTSDATETIME_QNAME, IVLTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ANY }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_ANY")
    public JAXBElement<ANY> createOBJETOANY(ANY value) {
        return new JAXBElement<ANY>(_OBJETOANY_QNAME, ANY.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EIVLTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_EIVLTSDATE")
    public JAXBElement<EIVLTSDATE> createOBJETOEIVLTSDATE(EIVLTSDATE value) {
        return new JAXBElement<EIVLTSDATE>(_OBJETOEIVLTSDATE_QNAME, EIVLTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETMO")
    public JAXBElement<QSETMO> createOBJETOQSETMO(QSETMO value) {
        return new JAXBElement<QSETMO>(_OBJETOQSETMO_QNAME, QSETMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETTSDATETIME")
    public JAXBElement<QSETTSDATETIME> createOBJETOQSETTSDATETIME(QSETTSDATETIME value) {
        return new JAXBElement<QSETTSDATETIME>(_OBJETOQSETTSDATETIME_QNAME, QSETTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSTS")
    public JAXBElement<QSSTS> createOBJETOQSSTS(QSSTS value) {
        return new JAXBElement<QSSTS>(_OBJETOQSSTS_QNAME, QSSTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHCO")
    public JAXBElement<IVLHIGHCO> createOBJETOIVLHIGHCO(IVLHIGHCO value) {
        return new JAXBElement<IVLHIGHCO>(_OBJETOIVLHIGHCO_QNAME, IVLHIGHCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CDCV }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_CDCV")
    public JAXBElement<CDCV> createOBJETOCDCV(CDCV value) {
        return new JAXBElement<CDCV>(_OBJETOCDCV_QNAME, CDCV.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHRTO")
    public JAXBElement<IVLHIGHRTO> createOBJETOIVLHIGHRTO(IVLHIGHRTO value) {
        return new JAXBElement<IVLHIGHRTO>(_OBJETOIVLHIGHRTO_QNAME, IVLHIGHRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUTS")
    public JAXBElement<QSUTS> createOBJETOQSUTS(QSUTS value) {
        return new JAXBElement<QSUTS>(_OBJETOQSUTS_QNAME, QSUTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUTSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUTSDATETIME")
    public JAXBElement<QSUTSDATETIME> createOBJETOQSUTSDATETIME(QSUTSDATETIME value) {
        return new JAXBElement<QSUTSDATETIME>(_OBJETOQSUTSDATETIME_QNAME, QSUTSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIINT")
    public JAXBElement<QSIINT> createOBJETOQSIINT(QSIINT value) {
        return new JAXBElement<QSIINT>(_OBJETOQSIINT_QNAME, QSIINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSIREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSIREAL")
    public JAXBElement<QSIREAL> createOBJETOQSIREAL(QSIREAL value) {
        return new JAXBElement<QSIREAL>(_OBJETOQSIREAL_QNAME, QSIREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSCO")
    public JAXBElement<QSSCO> createOBJETOQSSCO(QSSCO value) {
        return new JAXBElement<QSSCO>(_OBJETOQSSCO_QNAME, QSSCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDMO")
    public JAXBElement<QSDMO> createOBJETOQSDMO(QSDMO value) {
        return new JAXBElement<QSDMO>(_OBJETOQSDMO_QNAME, QSDMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDINT")
    public JAXBElement<QSDINT> createOBJETOQSDINT(QSDINT value) {
        return new JAXBElement<QSDINT>(_OBJETOQSDINT_QNAME, QSDINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUPQTIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUPQTIME")
    public JAXBElement<QSUPQTIME> createOBJETOQSUPQTIME(QSUPQTIME value) {
        return new JAXBElement<QSUPQTIME>(_OBJETOQSUPQTIME_QNAME, QSUPQTIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSITS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSITS")
    public JAXBElement<QSITS> createOBJETOQSITS(QSITS value) {
        return new JAXBElement<QSITS>(_OBJETOQSITS_QNAME, QSITS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ADXP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_ADXP")
    public JAXBElement<ADXP> createOBJETOADXP(ADXP value) {
        return new JAXBElement<ADXP>(_OBJETOADXP_QNAME, ADXP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHMO")
    public JAXBElement<IVLHIGHMO> createOBJETOIVLHIGHMO(IVLHIGHMO value) {
        return new JAXBElement<IVLHIGHMO>(_OBJETOIVLHIGHMO_QNAME, IVLHIGHMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EIVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_EIVLTS")
    public JAXBElement<EIVLTS> createOBJETOEIVLTS(EIVLTS value) {
        return new JAXBElement<EIVLTS>(_OBJETOEIVLTS_QNAME, EIVLTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPCO")
    public JAXBElement<QSPCO> createOBJETOQSPCO(QSPCO value) {
        return new JAXBElement<QSPCO>(_OBJETOQSPCO_QNAME, QSPCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLTS")
    public JAXBElement<IVLTS> createOBJETOIVLTS(IVLTS value) {
        return new JAXBElement<IVLTS>(_OBJETOIVLTS_QNAME, IVLTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLHIGHTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLHIGHTS")
    public JAXBElement<IVLHIGHTS> createOBJETOIVLHIGHTS(IVLHIGHTS value) {
        return new JAXBElement<IVLHIGHTS>(_OBJETOIVLHIGHTS_QNAME, IVLHIGHTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETCO")
    public JAXBElement<QSETCO> createOBJETOQSETCO(QSETCO value) {
        return new JAXBElement<QSETCO>(_OBJETOQSETCO_QNAME, QSETCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETRTO")
    public JAXBElement<QSETRTO> createOBJETOQSETRTO(QSETRTO value) {
        return new JAXBElement<QSETRTO>(_OBJETOQSETRTO_QNAME, QSETRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSMO")
    public JAXBElement<QSSMO> createOBJETOQSSMO(QSSMO value) {
        return new JAXBElement<QSSMO>(_OBJETOQSSMO_QNAME, QSSMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ENXP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_ENXP")
    public JAXBElement<ENXP> createOBJETOENXP(ENXP value) {
        return new JAXBElement<ENXP>(_OBJETOENXP_QNAME, ENXP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSDPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSDPQ")
    public JAXBElement<QSDPQ> createOBJETOQSDPQ(QSDPQ value) {
        return new JAXBElement<QSDPQ>(_OBJETOQSDPQ_QNAME, QSDPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSRTO")
    public JAXBElement<QSSRTO> createOBJETOQSSRTO(QSSRTO value) {
        return new JAXBElement<QSSRTO>(_OBJETOQSSRTO_QNAME, QSSRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWRTO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWRTO")
    public JAXBElement<IVLLOWRTO> createOBJETOIVLLOWRTO(IVLLOWRTO value) {
        return new JAXBElement<IVLLOWRTO>(_OBJETOIVLLOWRTO_QNAME, IVLLOWRTO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLWIDTHCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLWIDTHCO")
    public JAXBElement<IVLWIDTHCO> createOBJETOIVLWIDTHCO(IVLWIDTHCO value) {
        return new JAXBElement<IVLWIDTHCO>(_OBJETOIVLWIDTHCO_QNAME, IVLWIDTHCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XReference }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_XReference")
    public JAXBElement<XReference> createOBJETOXReference(XReference value) {
        return new JAXBElement<XReference>(_OBJETOXReference_QNAME, XReference.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWPQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWPQ")
    public JAXBElement<IVLLOWPQ> createOBJETOIVLLOWPQ(IVLLOWPQ value) {
        return new JAXBElement<IVLLOWPQ>(_OBJETOIVLLOWPQ_QNAME, IVLLOWPQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EHRExtract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iso.org/iso/search.htm?qt=13606", name = "ehrExtract")
    public JAXBElement<EHRExtract> createEhrExtract(EHRExtract value) {
        return new JAXBElement<EHRExtract>(_EhrExtract_QNAME, EHRExtract.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EHRExtract }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iso.org/iso/search.htm?qt=13606", name = "EHRExtract")
    public JAXBElement<EHRExtract> createEHRExtract(EHRExtract value) {
        return new JAXBElement<EHRExtract>(_EHRExtract_QNAME, EHRExtract.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETTS }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETTS")
    public JAXBElement<QSETTS> createOBJETOQSETTS(QSETTS value) {
        return new JAXBElement<QSETTS>(_OBJETOQSETTS_QNAME, QSETTS.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TSDATEFULL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_TSDATEFULL")
    public JAXBElement<TSDATEFULL> createOBJETOTSDATEFULL(TSDATEFULL value) {
        return new JAXBElement<TSDATEFULL>(_OBJETOTSDATEFULL_QNAME, TSDATEFULL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSSINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSSINT")
    public JAXBElement<QSSINT> createOBJETOQSSINT(QSSINT value) {
        return new JAXBElement<QSSINT>(_OBJETOQSSINT_QNAME, QSSINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_AD")
    public JAXBElement<AD> createOBJETOAD(AD value) {
        return new JAXBElement<AD>(_OBJETOAD_QNAME, AD.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLWIDTHTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLWIDTHTSDATE")
    public JAXBElement<IVLWIDTHTSDATE> createOBJETOIVLWIDTHTSDATE(IVLWIDTHTSDATE value) {
        return new JAXBElement<IVLWIDTHTSDATE>(_OBJETOIVLWIDTHTSDATE_QNAME, IVLWIDTHTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLTSDATE")
    public JAXBElement<IVLTSDATE> createOBJETOIVLTSDATE(IVLTSDATE value) {
        return new JAXBElement<IVLTSDATE>(_OBJETOIVLTSDATE_QNAME, IVLTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWINT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWINT")
    public JAXBElement<IVLLOWINT> createOBJETOIVLLOWINT(IVLLOWINT value) {
        return new JAXBElement<IVLLOWINT>(_OBJETOIVLLOWINT_QNAME, IVLLOWINT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUCO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUCO")
    public JAXBElement<QSUCO> createOBJETOQSUCO(QSUCO value) {
        return new JAXBElement<QSUCO>(_OBJETOQSUCO_QNAME, QSUCO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PQ")
    public JAXBElement<PQ> createOBJETOPQ(PQ value) {
        return new JAXBElement<PQ>(_OBJETOPQ_QNAME, PQ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSETBOUNDEDPIVL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSETBOUNDEDPIVL")
    public JAXBElement<QSETBOUNDEDPIVL> createOBJETOQSETBOUNDEDPIVL(QSETBOUNDEDPIVL value) {
        return new JAXBElement<QSETBOUNDEDPIVL>(_OBJETOQSETBOUNDEDPIVL_QNAME, QSETBOUNDEDPIVL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSITSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSITSDATE")
    public JAXBElement<QSITSDATE> createOBJETOQSITSDATE(QSITSDATE value) {
        return new JAXBElement<QSITSDATE>(_OBJETOQSITSDATE_QNAME, QSITSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EDTEXT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_EDTEXT")
    public JAXBElement<EDTEXT> createOBJETOEDTEXT(EDTEXT value) {
        return new JAXBElement<EDTEXT>(_OBJETOEDTEXT_QNAME, EDTEXT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQR }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PQR")
    public JAXBElement<PQR> createOBJETOPQR(PQR value) {
        return new JAXBElement<PQR>(_OBJETOPQR_QNAME, PQR.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLLOWREAL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLLOWREAL")
    public JAXBElement<IVLLOWREAL> createOBJETOIVLLOWREAL(IVLLOWREAL value) {
        return new JAXBElement<IVLLOWREAL>(_OBJETOIVLLOWREAL_QNAME, IVLLOWREAL.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PQV }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_PQV")
    public JAXBElement<PQV> createOBJETOPQV(PQV value) {
        return new JAXBElement<PQV>(_OBJETOPQV_QNAME, PQV.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSUMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSUMO")
    public JAXBElement<QSUMO> createOBJETOQSUMO(QSUMO value) {
        return new JAXBElement<QSUMO>(_OBJETOQSUMO_QNAME, QSUMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IVLMO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_IVLMO")
    public JAXBElement<IVLMO> createOBJETOIVLMO(IVLMO value) {
        return new JAXBElement<IVLMO>(_OBJETOIVLMO_QNAME, IVLMO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSPTSDATE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSPTSDATE")
    public JAXBElement<QSPTSDATE> createOBJETOQSPTSDATE(QSPTSDATE value) {
        return new JAXBElement<QSPTSDATE>(_OBJETOQSPTSDATE_QNAME, QSPTSDATE.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QSITSDATETIME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_QSITSDATETIME")
    public JAXBElement<QSITSDATETIME> createOBJETOQSITSDATETIME(QSITSDATETIME value) {
        return new JAXBElement<QSITSDATETIME>(_OBJETOQSITSDATETIME_QNAME, QSITSDATETIME.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link II }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "uri:iso.org:21090", name = "OBJETO_II")
    public JAXBElement<II> createOBJETOII(II value) {
        return new JAXBElement<II>(_OBJETOII_QNAME, II.class, null, value);
    }

}
