//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:iso.org:21090", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sigaim.siie.iso13606.rm;
