//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Superclass  of all concrete  aggregator classes in  the EHR
 *         hierarchy. archetypeId is changed to type II (from String).
 *         Please  note  the  possible   disclosure  implications   of
 *         including all policyIds when providing an EHRExtract  (that
 *         the  recipient would  then know the policies  governing all
 *         other recipients).  sensitivity is  changed to  part 4 type
 *         Sensitivity.
 *       
 * 
 * <p>Java class for RecordComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecordComponent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archetypeId" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="meaning" type="{uri:iso.org:21090}CD.CV" minOccurs="0"/>
 *         &lt;element name="name" type="{uri:iso.org:21090}CD.CV"/>
 *         &lt;element name="origParentRef" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="policyIds" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rcId" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="sensitivity" type="{http://www.iso.org/iso/search.htm?qt=13606}Sensitivity" minOccurs="0"/>
 *         &lt;element name="synthesised" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="links" type="{http://www.iso.org/iso/search.htm?qt=13606}Link" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="feederAudit" type="{http://www.iso.org/iso/search.htm?qt=13606}AuditInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecordComponent", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "archetypeId",
    "meaning",
    "name",
    "origParentRef",
    "policyIds",
    "rcId",
    "sensitivity",
    "synthesised",
    "links",
    "feederAudit"
})
@XmlSeeAlso({
    Composition.class,
    Folder.class,
    Content.class,
    Item.class
})
public abstract class RecordComponent {

    @XmlElement(namespace = "")
    protected II archetypeId;
    @XmlElement(namespace = "")
    protected CDCV meaning;
    @XmlElement(namespace = "", required = true)
    protected CDCV name;
    @XmlElement(namespace = "")
    protected II origParentRef;
    @XmlElement(namespace = "")
    protected List<II> policyIds;
    @XmlElement(namespace = "", required = true)
    protected II rcId;
    @XmlElement(namespace = "")
    protected BigInteger sensitivity;
    @XmlElement(namespace = "")
    protected boolean synthesised;
    @XmlElement(namespace = "")
    protected List<Link> links;
    @XmlElement(namespace = "")
    protected AuditInfo feederAudit;

    /**
     * Gets the value of the archetypeId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getArchetypeId() {
        return archetypeId;
    }

    /**
     * Sets the value of the archetypeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setArchetypeId(II value) {
        this.archetypeId = value;
    }

    /**
     * Gets the value of the meaning property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getMeaning() {
        return meaning;
    }

    /**
     * Sets the value of the meaning property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setMeaning(CDCV value) {
        this.meaning = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setName(CDCV value) {
        this.name = value;
    }

    /**
     * Gets the value of the origParentRef property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getOrigParentRef() {
        return origParentRef;
    }

    /**
     * Sets the value of the origParentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setOrigParentRef(II value) {
        this.origParentRef = value;
    }

    /**
     * Gets the value of the policyIds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the policyIds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPolicyIds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getPolicyIds() {
        if (policyIds == null) {
            policyIds = new ArrayList<II>();
        }
        return this.policyIds;
    }

    /**
     * Gets the value of the rcId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getRcId() {
        return rcId;
    }

    /**
     * Sets the value of the rcId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setRcId(II value) {
        this.rcId = value;
    }

    /**
     * Gets the value of the sensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSensitivity() {
        return sensitivity;
    }

    /**
     * Sets the value of the sensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSensitivity(BigInteger value) {
        this.sensitivity = value;
    }

    /**
     * Gets the value of the synthesised property.
     * 
     */
    public boolean isSynthesised() {
        return synthesised;
    }

    /**
     * Sets the value of the synthesised property.
     * 
     */
    public void setSynthesised(boolean value) {
        this.synthesised = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Link }
     * 
     * 
     */
    public List<Link> getLinks() {
        if (links == null) {
            links = new ArrayList<Link>();
        }
        return this.links;
    }

    /**
     * Gets the value of the feederAudit property.
     * 
     * @return
     *     possible object is
     *     {@link AuditInfo }
     *     
     */
    public AuditInfo getFeederAudit() {
        return feederAudit;
    }

    /**
     * Sets the value of the feederAudit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditInfo }
     *     
     */
    public void setFeederAudit(AuditInfo value) {
        this.feederAudit = value;
    }

}
