//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Identifies the relationship  of a person to the  subject of
 *         care. Specifically used in Entry.subjectOfInformation.
 *       
 * 
 * <p>Java class for RelatedParty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedParty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="party" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="relationship" type="{uri:iso.org:21090}CD.CV"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedParty", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "party",
    "relationship"
})
public class RelatedParty {

    @XmlElement(namespace = "")
    protected II party;
    @XmlElement(namespace = "", required = true)
    protected CDCV relationship;

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setParty(II value) {
        this.party = value;
    }

    /**
     * Gets the value of the relationship property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getRelationship() {
        return relationship;
    }

    /**
     * Sets the value of the relationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setRelationship(CDCV value) {
        this.relationship = value;
    }

}
