//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         Defines the  properties of  the  requestors to  which  this
 *         policy  applies.   If  no  requestor  characteristics   are
 *         specified  then the  policy  applies to all requests.  Note
 *         that  CS_FUNC_ROLE  refers  to the  FunctionalRoles  class,
 *         despite that  not being named  as such in the  standard and
 *         not described therein  as a CS.  CS_SETTING is not given at
 *         all and becomes a CD.CV here.
 *       
 * 
 * <p>Java class for Request complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Request">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="functionalRoles" type="{http://www.iso.org/iso/search.htm?qt=13606}FunctionalRoles" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="structuralRoles" type="{uri:iso.org:21090}CD.CV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="clinicalSettings" type="{uri:iso.org:21090}CD.CV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="specialities" type="{uri:iso.org:21090}CD.CV" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="parties" type="{uri:iso.org:21090}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="otherCharacteristics" type="{uri:iso.org:21090}CD.CV" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Request", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "functionalRoles",
    "structuralRoles",
    "clinicalSettings",
    "specialities",
    "parties",
    "otherCharacteristics"
})
public class Request {

    @XmlElement(namespace = "")
    protected List<FunctionalRoles> functionalRoles;
    @XmlElement(namespace = "")
    protected List<CDCV> structuralRoles;
    @XmlElement(namespace = "")
    protected List<CDCV> clinicalSettings;
    @XmlElement(namespace = "")
    protected List<CDCV> specialities;
    @XmlElement(namespace = "")
    protected List<II> parties;
    @XmlElement(namespace = "")
    protected List<CDCV> otherCharacteristics;

    /**
     * Gets the value of the functionalRoles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the functionalRoles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunctionalRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FunctionalRoles }
     * 
     * 
     */
    public List<FunctionalRoles> getFunctionalRoles() {
        if (functionalRoles == null) {
            functionalRoles = new ArrayList<FunctionalRoles>();
        }
        return this.functionalRoles;
    }

    /**
     * Gets the value of the structuralRoles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the structuralRoles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStructuralRoles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDCV }
     * 
     * 
     */
    public List<CDCV> getStructuralRoles() {
        if (structuralRoles == null) {
            structuralRoles = new ArrayList<CDCV>();
        }
        return this.structuralRoles;
    }

    /**
     * Gets the value of the clinicalSettings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clinicalSettings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClinicalSettings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDCV }
     * 
     * 
     */
    public List<CDCV> getClinicalSettings() {
        if (clinicalSettings == null) {
            clinicalSettings = new ArrayList<CDCV>();
        }
        return this.clinicalSettings;
    }

    /**
     * Gets the value of the specialities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDCV }
     * 
     * 
     */
    public List<CDCV> getSpecialities() {
        if (specialities == null) {
            specialities = new ArrayList<CDCV>();
        }
        return this.specialities;
    }

    /**
     * Gets the value of the parties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link II }
     * 
     * 
     */
    public List<II> getParties() {
        if (parties == null) {
            parties = new ArrayList<II>();
        }
        return this.parties;
    }

    /**
     * Gets the value of the otherCharacteristics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherCharacteristics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherCharacteristics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDCV }
     * 
     * 
     */
    public List<CDCV> getOtherCharacteristics() {
        if (otherCharacteristics == null) {
            otherCharacteristics = new ArrayList<CDCV>();
        }
        return this.otherCharacteristics;
    }

}
