//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.04 at 02:11:57 AM CEST 
//


package org.sigaim.siie.iso13606.rm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         A piece of equipment or a device.
 *       
 * 
 * <p>Java class for SoftwareOrDevice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareOrDevice">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iso.org/iso/search.htm?qt=13606}IdentifiedEntity">
 *       &lt;sequence>
 *         &lt;element name="code" type="{uri:iso.org:21090}CD.CV"/>
 *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manufacturerModelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="owningOrganisationId" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareOrDevice", namespace = "http://www.iso.org/iso/search.htm?qt=13606", propOrder = {
    "code",
    "desc",
    "manufacturerModelName",
    "version",
    "owningOrganisationId"
})
public class SoftwareOrDevice
    extends IdentifiedEntity
{

    @XmlElement(namespace = "", required = true)
    protected CDCV code;
    @XmlElement(namespace = "", required = true)
    protected String desc;
    @XmlElement(namespace = "", required = true)
    protected String manufacturerModelName;
    @XmlElement(namespace = "")
    protected String version;
    @XmlElement(namespace = "")
    protected II owningOrganisationId;

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CDCV }
     *     
     */
    public CDCV getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CDCV }
     *     
     */
    public void setCode(CDCV value) {
        this.code = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the manufacturerModelName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerModelName() {
        return manufacturerModelName;
    }

    /**
     * Sets the value of the manufacturerModelName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerModelName(String value) {
        this.manufacturerModelName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the owningOrganisationId property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getOwningOrganisationId() {
        return owningOrganisationId;
    }

    /**
     * Sets the value of the owningOrganisationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setOwningOrganisationId(II value) {
        this.owningOrganisationId = value;
    }

}
